(function () {
    var BASE = "https://mumcofuervklloaotpih.supabase.co/functions/v1/metrics-pwa";
    var CATEGORY_NAMES = { body: "身体", health: "健康", mindfulness: "正念", medicine: "药物", supplement: "补剂", food: "食物", learning: "学习", media: "媒体", media_sleep: "媒体睡眠", mood_productivity: "心情效率", productivity: "效率", sleep: "睡眠", habit: "习惯", pet: "宠物", general: "其他" };
    var CATEGORY_ORDER = ["body", "health", "mindfulness", "sleep", "mood_productivity", "productivity", "medicine", "supplement", "food", "learning", "media", "media_sleep", "habit", "pet", "general"];
    var DEFAULT_PINNED = ["body_weight_clothed_jin", "blood_glucose_yuyue550", "blood_glucose_post_meal_hours", "atomoxetine_total_mg", "eggs_count", "daily_nuts_bag_count", "reading_or_audiobook", "learn_english_on_x", "watched_financial_news"];
    var state = { authed: false, date: shanghaiDate(0), defs: [], values: {}, latest: {}, events: [], dirty: {}, filter: localStorage.getItem("metricsPwaFilter") || "unfilled", query: "", expanded: {}, pinned: loadPinned(), token: localStorage.getItem("metricsPwaToken") || "", queue: loadQueue(), mindfulness: null, mindfulLoading: false, mindfulAction: false, trend: { metric: localStorage.getItem("metricsPwaTrendMetric") || "", days: Number(localStorage.getItem("metricsPwaTrendDays") || 90), data: null, loading: false }, backfillOpen: false, backfillPreview: null, backfillTouchedStart: false, backfill: { metric: "", value: "", start: "", end: "" } };
    var el = { login: document.getElementById("login"), app: document.getElementById("app"), loginForm: document.getElementById("loginForm"), passphrase: document.getElementById("passphrase"), loginMsg: document.getElementById("loginMsg"), dateInput: document.getElementById("dateInput"), status: document.getElementById("status"), todayPanel: document.getElementById("todayPanel"), modeTabs: document.getElementById("modeTabs"), searchInput: document.getElementById("searchInput"), clearSearch: document.getElementById("clearSearch"), filters: document.getElementById("filters"), useLatestBtn: document.getElementById("useLatestBtn"), firstMissingBtn: document.getElementById("firstMissingBtn"), backfillToggle: document.getElementById("backfillToggle"), scopeLabel: document.getElementById("scopeLabel"), dirtyLabel: document.getElementById("dirtyLabel"), content: document.getElementById("content"), pending: document.getElementById("pending"), undoBtn: document.getElementById("undoBtn"), saveBtn: document.getElementById("saveBtn"), toast: document.getElementById("toast") };
    var trendLoadSeq = 0;
    var mindfulTick = null;
    var mindfulEndHoldTimer = null;
    var mindfulReturnClickAt = 0;
    var refreshingForUpdate = false;
    var launchIntent = readLaunchIntent();
    function readLaunchIntent() { var params = new URLSearchParams(window.location.search); var mode = params.get("mode") || ""; var mindful = params.get("mindful") || ""; if (["start", "return", "end"].indexOf(mindful) === -1) mindful = ""; if (mode === "mindfulness" || mindful) { state.filter = "mindfulness"; localStorage.setItem("metricsPwaFilter", state.filter); } if (mode || mindful) { history.replaceState(null, "", window.location.pathname + window.location.hash); } return { mindful: mindful }; }
    function shanghaiDate(offset) { var base = new Date(Date.now() + offset * 86400000); var parts = new Intl.DateTimeFormat("en-US", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(base); var out = {}; parts.forEach(function (part) { out[part.type] = part.value; }); return out.year + "-" + out.month + "-" + out.day; }
    function shanghaiTime() { return new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Shanghai", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date()); }
    function addDays(date, offset) { var parts = date.split("-").map(Number); var d = new Date(Date.UTC(parts[0], parts[1] - 1, parts[2] + offset)); return d.toISOString().slice(0, 10); }
    function enumerateDateStrings(start, end) { var out = []; var cursor = start; var guard = 0; while (cursor <= end && guard < 800) { out.push(cursor); cursor = addDays(cursor, 1); guard += 1; } return out; }
    function uid() { return "pwa-" + Date.now() + "-" + Math.random().toString(16).slice(2); }
    function showToast(text) { el.toast.textContent = text; el.toast.classList.add("show"); setTimeout(function () { el.toast.classList.remove("show"); }, 1800); }
    function setStatus(text) { el.status.textContent = text; }
    function loadQueue() { try { return JSON.parse(localStorage.getItem("metricsPwaQueue") || "[]"); } catch (_) { return []; } }
    function cleanPinnedKeys(keys) { var out = []; if (!Array.isArray(keys)) return out; keys.forEach(function (item) { var key = String(item || "").trim(); if (/^[a-z][a-z0-9_]*$/.test(key) && out.indexOf(key) === -1) out.push(key); }); return out; }
    function localPinnedValue() { try { var saved = JSON.parse(localStorage.getItem("metricsPwaPinnedKeys") || "null"); return Array.isArray(saved) ? cleanPinnedKeys(saved) : null; } catch (_) { return null; } }
    function loadPinned() { var saved = localPinnedValue(); return Array.isArray(saved) ? saved : DEFAULT_PINNED.slice(); }
    function savePinned() { localStorage.setItem("metricsPwaPinnedKeys", JSON.stringify(cleanPinnedKeys(state.pinned))); }
    function saveQueue() { localStorage.setItem("metricsPwaQueue", JSON.stringify(state.queue)); updateFooter(); }
    function enqueue(item) { state.queue.push(item); saveQueue(); showToast("已加入待同步"); }
    function cacheKeyForDay(date) { return "metricsPwaDay:" + date; }
    function saveSchemaCache(defs) { localStorage.setItem("metricsPwaSchema", JSON.stringify({ cached_at: new Date().toISOString(), definitions: defs })); }
    function saveDayCache(date, data) { localStorage.setItem(cacheKeyForDay(date), JSON.stringify({ cached_at: new Date().toISOString(), data: data })); }
    function readJson(key) { try { return JSON.parse(localStorage.getItem(key) || "null"); } catch (_) { return null; } }
    function hydrateFromCache() { var schema = readJson("metricsPwaSchema"); var day = readJson(cacheKeyForDay(state.date)); var used = false; if (schema && Array.isArray(schema.definitions)) { state.defs = schema.definitions; used = true; } if (day && day.data) { state.values = day.data.values || {}; state.latest = day.data.latest_values || {}; state.events = day.data.events || []; used = true; } if (used) { renderAll(); setStatus("本地缓存"); } }
    async function api(path, options) { var opts = options || {}; opts.credentials = "same-origin"; opts.headers = Object.assign({ "content-type": "application/json" }, opts.headers || {}); if (state.token) opts.headers.Authorization = "Bearer " + state.token; var res = await fetch(BASE + path, opts); var data = await res.json().catch(function () { return {}; }); if (res.status === 401) { state.authed = false; state.token = ""; localStorage.removeItem("metricsPwaToken"); showLogin(); throw new Error("Unauthorized"); } if (!res.ok || data.ok === false) throw new Error(data.error || "请求失败"); return data; }
    async function sendOrQueue(path, method, body) { var item = { id: uid(), path: path, method: method, body: body, created_at: new Date().toISOString() }; if (!navigator.onLine) { enqueue(item); return { queued: true }; } try { return await api(path, { method: method, body: JSON.stringify(body) }); } catch (err) { if (String(err.message) !== "Unauthorized") enqueue(item); throw err; } }
    async function flushQueue() { if (!state.queue.length || !navigator.onLine) { saveQueue(); return; } var next = []; for (var i = 0; i < state.queue.length; i += 1) { var item = state.queue[i]; try { await api(item.path, { method: item.method, body: JSON.stringify(item.body) }); } catch (err) { next = state.queue.slice(i); break; } } state.queue = next; saveQueue(); if (!state.queue.length) { showToast("同步完成"); await loadDay(); } }
    async function loadPreferences() { if (localStorage.getItem("metricsPwaPinnedPending") === "1") { await savePreferences(); return; } var localPinned = localPinnedValue(); var localNeedsMigration = Array.isArray(localPinned) && localStorage.getItem("metricsPwaPinnedSynced") !== "1"; try { setStatus("读取收藏"); var data = await api("/api/preferences"); var prefs = data.preferences || {}; if (localNeedsMigration) { state.pinned = localPinned; savePinned(); await savePreferences(); setStatus("本地收藏已迁移"); return; } if (data.exists && Array.isArray(prefs.pinned_metric_keys)) { state.pinned = cleanPinnedKeys(prefs.pinned_metric_keys); savePinned(); localStorage.setItem("metricsPwaPinnedSynced", "1"); renderAll(); setStatus("收藏已同步"); return; } state.pinned = loadPinned(); savePinned(); await savePreferences(); setStatus("收藏已迁移"); } catch (err) { setStatus("本地收藏"); } }
    async function savePreferences() { savePinned(); if (!navigator.onLine) { localStorage.setItem("metricsPwaPinnedPending", "1"); setStatus("收藏待同步"); return; } try { await api("/api/preferences", { method: "POST", body: JSON.stringify({ pinned_metric_keys: cleanPinnedKeys(state.pinned) }) }); localStorage.removeItem("metricsPwaPinnedPending"); localStorage.setItem("metricsPwaPinnedSynced", "1"); setStatus("收藏已同步"); } catch (err) { if (String(err.message) !== "Unauthorized") { localStorage.setItem("metricsPwaPinnedPending", "1"); setStatus("收藏待同步"); } } }
    async function syncAll() { await flushQueue(); await syncPendingPreferences(); }
    async function syncPendingPreferences() { if (localStorage.getItem("metricsPwaPinnedPending") === "1") await savePreferences(); }
    function showLogin() { el.login.classList.remove("hidden"); el.app.classList.add("hidden"); setTimeout(function () { el.passphrase.focus(); }, 50); }
    function showApp() { el.login.classList.add("hidden"); el.app.classList.remove("hidden"); }
    async function boot() { registerSW(); saveQueue(); el.dateInput.value = state.date; bindEvents(); if (state.token) { showApp(); hydrateFromCache(); } else { showLogin(); } try { if (state.token) await api("/api/session"); state.authed = true; showApp(); await loadSchema(); await loadPreferences(); await loadDay(); await syncAll(); await handleLaunchIntent(); } catch (err) { console.error("metrics-pwa boot failed", err); if (!state.defs.length) showLogin(); } }
    function registerSW() { if ("serviceWorker" in navigator) { navigator.serviceWorker.addEventListener("controllerchange", function () { if (refreshingForUpdate) return; refreshingForUpdate = true; window.location.reload(); }); navigator.serviceWorker.register("/personal-metrics-pwa/sw.js", { scope: "/personal-metrics-pwa/" }).then(function (registration) { registration.update().catch(function () {}); }).catch(function () {}); } }
    function bindEvents() {
      el.loginForm.addEventListener("submit", async function (event) {
        event.preventDefault();
        el.loginMsg.textContent = "验证中";
        try {
          var result = await api("/api/login", { method: "POST", body: JSON.stringify({ passphrase: el.passphrase.value }) });
          state.token = result.token || "";
          if (state.token) localStorage.setItem("metricsPwaToken", state.token);
          el.passphrase.value = "";
          state.authed = true;
          showApp();
          await loadSchema();
          await loadPreferences();
          await loadDay();
          await handleLaunchIntent();
          el.loginMsg.textContent = "";
        } catch (err) {
          el.loginMsg.textContent = "口令不对或尝试过多";
        }
      });
      document.getElementById("todayBtn").addEventListener("click", function () { changeDate(shanghaiDate(0)); });
      document.getElementById("prevDay").addEventListener("click", function () { changeDate(addDays(state.date, -1)); });
      document.getElementById("nextDay").addEventListener("click", function () { changeDate(addDays(state.date, 1)); });
      el.dateInput.addEventListener("change", function () { changeDate(el.dateInput.value); });
      el.searchInput.addEventListener("input", function () { state.query = el.searchInput.value.trim(); renderAll(); });
      el.clearSearch.addEventListener("click", function () { el.searchInput.value = ""; state.query = ""; renderAll(); });
      el.saveBtn.addEventListener("click", saveDirty);
      document.getElementById("syncBtn").addEventListener("click", syncAll);
      el.undoBtn.addEventListener("click", undoDirty);
      el.useLatestBtn.addEventListener("click", useLatestForPinned);
      el.firstMissingBtn.addEventListener("click", focusFirstMissing);
      el.backfillToggle.addEventListener("click", toggleBackfill);
      window.addEventListener("online", syncAll);
      el.modeTabs.addEventListener("click", handleFilterClick);
      el.filters.addEventListener("click", handleFilterClick);
      el.content.addEventListener("input", handleInput);
      el.content.addEventListener("change", handleChange);
      el.content.addEventListener("click", handleClick);
      el.app.addEventListener("click", handleMindfulScreenTap, true);
      el.app.addEventListener("pointerdown", handleMindfulEndHoldStart, true);
      el.app.addEventListener("pointerup", clearMindfulEndHold, true);
      el.app.addEventListener("pointercancel", clearMindfulEndHold, true);
      el.app.addEventListener("pointerleave", clearMindfulEndHold, true);
    }
    function handleFilterClick(event) { var btn = event.target.closest("button[data-filter]"); if (!btn) return; state.filter = btn.dataset.filter; localStorage.setItem("metricsPwaFilter", state.filter); renderAll(); if (state.filter === "mindfulness") loadMindfulness(); if (state.filter === "trend") loadTrend(); }
    async function changeDate(date) { state.date = date; el.dateInput.value = date; state.dirty = {}; var cached = readJson(cacheKeyForDay(date)); if (cached && cached.data) { state.values = cached.data.values || {}; state.latest = cached.data.latest_values || {}; state.events = cached.data.events || []; renderAll(); setStatus("本地缓存"); } await loadDay(); }
    async function loadSchema() { setStatus("加载字段"); var data = await api("/api/schema"); state.defs = data.definitions || []; saveSchemaCache(state.defs); renderAll(); }
    async function loadDay() { setStatus("读取中"); var data = await api("/api/day?date=" + encodeURIComponent(state.date)); state.values = data.values || {}; state.latest = data.latest_values || {}; state.events = data.events || []; saveDayCache(state.date, data); renderAll(); setStatus("已读取"); await loadMindfulness(); if (state.filter === "trend") loadTrend(); }
    async function loadMindfulness() { if (state.mindfulLoading) return; state.mindfulLoading = true; try { var data = await api("/api/mindfulness/today?date=" + encodeURIComponent(state.date)); state.mindfulness = data.today || null; } catch (err) {} finally { state.mindfulLoading = false; renderAll(); } }
    async function handleLaunchIntent() { if (state.filter !== "mindfulness" && !launchIntent.mindful) return; state.filter = "mindfulness"; localStorage.setItem("metricsPwaFilter", state.filter); renderAll(); await loadMindfulness(); if (!launchIntent.mindful) return; var action = launchIntent.mindful; launchIntent.mindful = ""; await runMindfulAction(action); }
    function renderAll() { renderTodayPanel(); renderFilters(); renderContent(); updateFooter(); manageMindfulTimer(); updateMindfulActiveMode(); }
    function renderTodayPanel() { var pinned = pinnedDefs(); var filled = pinned.filter(hasValueFor).length; var total = pinned.length || 1; var missing = Math.max(total - filled, 0); var dirtyCount = Object.keys(state.dirty).length; var pct = Math.round(filled / total * 100); var latestUsable = pinned.filter(function (def) { return !hasValueFor(def) && latestFor(def); }).length; el.todayPanel.innerHTML = '<div class="today-top"><div><div class="today-title">今天还差 ' + missing + ' 项</div><div class="today-sub">' + escapeHtml(state.date) + ' · 常用 ' + filled + '/' + total + ' · ' + (latestUsable ? latestUsable + ' 项可沿用上次值' : '没有可直接沿用的常用项') + '</div></div><div class="stat"><b>' + pct + '%</b><span>完成</span></div></div><div class="progress-track"><div class="progress-fill" style="width:' + pct + '%"></div></div><div class="stats"><div class="stat"><b>' + filled + '</b><span>常用已填</span></div><div class="stat"><b>' + missing + '</b><span>常用待填</span></div><div class="stat"><b>' + dirtyCount + '</b><span>未保存</span></div></div>'; el.useLatestBtn.disabled = latestUsable === 0; }
    function renderFilters() { var modes = [{ key: "unfilled", name: "待填", count: unfilledDefs().length }, { key: "pinned", name: "常用", count: pinnedDefs().length }, { key: "mindfulness", name: "正念", count: "" }, { key: "filled", name: "已填", count: filledDefs().length }, { key: "trend", name: "趋势", count: "" }, { key: "all", name: "全部", count: editableDefs().length }]; el.modeTabs.innerHTML = modes.map(function (chip) { return '<button type="button" data-filter="' + escapeAttr(chip.key) + '" class="' + (state.filter === chip.key ? 'active' : '') + '">' + escapeHtml(chip.name + (chip.count !== "" ? " " + chip.count : "")) + '</button>'; }).join(""); var cats = categories(); el.filters.innerHTML = cats.map(function (cat) { var key = "cat:" + cat; return '<button type="button" data-filter="' + escapeAttr(key) + '" class="' + (state.filter === key ? 'active' : '') + '">' + escapeHtml(CATEGORY_NAMES[cat] || cat) + ' ' + defsForCategory(cat).length + '</button>'; }).join(""); el.clearSearch.classList.toggle("hidden", !state.query); }
    function renderContent() { if (state.filter === "mindfulness") { el.content.innerHTML = renderMindfulnessPanel(); el.scopeLabel.textContent = "正念 · 今日"; return; } if (state.filter === "trend") { el.content.innerHTML = renderTrendPanel(); el.scopeLabel.textContent = "趋势 · " + trendTitle(); fillTrendControls(); return; } var defs = visibleDefs(); var title = scopeTitle(); var dirtyCount = Object.keys(state.dirty).length; var html = renderBackfillPanel(); html += '<div class="section-head"><h2>' + escapeHtml(title) + '</h2><span>' + escapeHtml(helperText()) + '</span></div>'; if (!defs.length && dirtyCount && state.filter === "unfilled" && !state.query) html += '<div class="done-card"><b>待填常用已放进待保存清单</b><span>底部显示“保存 ' + dirtyCount + '”。你还可以切到“常用”逐项检查，或直接保存。</span></div>'; else if (!defs.length) html += '<div class="empty">没有匹配字段。可以搜索字段，或切到“全部”。</div>'; else if (state.filter === "filled" && !state.query) html += renderDenseFilled(defs); else html += '<div class="metric-list">' + defs.map(renderMetric).join("") + '</div>'; el.content.innerHTML = html; el.scopeLabel.textContent = title + ' · 显示 ' + defs.length + ' 项'; fillBackfillControls(); }
    function mindfulActive() { return state.mindfulness && state.mindfulness.active_session; }
    function isMindfulActiveView() { return state.filter === "mindfulness" && !!mindfulActive(); }
    function updateMindfulActiveMode() { document.body.classList.toggle("mindful-active-mode", isMindfulActiveView()); }
    function activeMindfulSeconds() { var active = mindfulActive(); if (!active || !active.started_at) return 0; return Math.max(0, Math.round((Date.now() - Date.parse(active.started_at)) / 1000)); }
    function mindfulTotals() { var today = state.mindfulness || {}; var summary = today.summary || {}; var completed = Number(summary.completed_seconds || 0); var active = activeMindfulSeconds(); var total = completed + active; var minutes = Math.round(total / 60 * 100) / 100; var returns = Number(summary.return_count || 0); return { sessions: Number(summary.session_count || 0), returns: returns, total_seconds: total, minutes: minutes, density: minutes > 0 ? Math.round(returns / minutes * 100) / 100 : null, active_seconds: active }; }
    function renderMindfulnessPanel() { var totals = mindfulTotals(); var active = mindfulActive(); var sessions = (state.mindfulness && state.mindfulness.sessions) || []; if (active) return renderMindfulnessActivePanel(totals, sessions); var html = '<div class="mindful-panel"><section class="mindful-card"><div class="mindful-hero"><div class="mindful-state"><b>今天的正念</b><span>开始时点一次，结束时长按；练习中随意点屏幕就是一次拉回。</span></div><div class="mindful-timer"><b>' + escapeHtml(formatDuration(totals.total_seconds)) + '</b><span>今日</span></div></div><div class="mindful-actions"><button class="primary" type="button" data-mindful-action="start" ' + (state.mindfulAction ? 'disabled' : '') + '>开始正念</button></div><div class="mindful-stats"><div class="mindful-stat"><b>' + escapeHtml(String(totals.sessions)) + '</b><span>会话次数</span></div><div class="mindful-stat"><b>' + escapeHtml(formatMinutes(totals.minutes)) + '</b><span>总时长</span></div><div class="mindful-stat"><b>' + escapeHtml(String(totals.returns)) + '</b><span>拉回次数</span></div><div class="mindful-stat"><b>' + escapeHtml(totals.density == null ? '—' : String(totals.density)) + '</b><span>次/分钟</span></div></div><div class="mindful-note">拉回密度只能看趋势：下降可能是注意更稳，也可能是走神后没发现。这里不做 KPI，只帮你看见练习。</div></section>'; html += '<section class="mindful-card"><div class="section-head"><h2>今日会话</h2><span>' + escapeHtml(state.date) + '</span></div>' + renderMindfulSessions(sessions) + '</section></div>'; return html; }
    function renderMindfulnessActivePanel(totals, sessions) { return '<div class="mindful-active-screen"><section class="mindful-tap-zone" data-mindful-tap role="button" tabindex="0" aria-label="点任意位置记录一次拉回"><div class="mindful-active-top"><span>正念进行中</span><b>' + escapeHtml(formatDuration(totals.active_seconds || totals.total_seconds)) + '</b><small>闭眼时不用找按钮：点到屏幕任何位置，都会记一次拉回。</small></div><div class="mindful-active-count"><b>' + escapeHtml(String(totals.returns)) + '</b><span>拉回次数</span></div><div class="mindful-active-grid"><div><b>' + escapeHtml(String(totals.sessions)) + '</b><span>会话</span></div><div><b>' + escapeHtml(formatMinutes(totals.minutes)) + '</b><span>总时长</span></div><div><b>' + escapeHtml(totals.density == null ? '—' : String(totals.density)) + '</b><span>次/分钟</span></div></div></section><section class="mindful-end-zone"><button class="mindful-end-hold" type="button" data-mindful-end-hold ' + (state.mindfulAction ? 'disabled' : '') + '>长按结束</button><span>普通点击不会结束，也不会记拉回。按住到震动/提示后才结束。</span></section><section class="mindful-card mindful-active-history"><div class="section-head"><h2>今日会话</h2><span>' + escapeHtml(state.date) + '</span></div>' + renderMindfulSessions(sessions) + '</section></div>'; }
    function renderMindfulSessions(sessions) { if (!sessions.length) return '<div class="empty">今天还没有正念会话。</div>'; return '<div class="history-list">' + sessions.slice(0, 8).map(function (session) { var seconds = session.status === "active" ? activeMindfulSeconds() : Number(session.duration_seconds || 0); return '<div class="history-row"><div class="date">' + escapeHtml(shortClock(session.started_at)) + '</div><div class="value">' + escapeHtml(formatDuration(seconds) + ' · 拉回 ' + (session.return_count || 0)) + '</div><div class="source">' + escapeHtml(session.status === "active" ? "进行中" : "已结束") + '</div></div>'; }).join("") + '</div>'; }
    function manageMindfulTimer() { var shouldRun = !!mindfulActive(); if (shouldRun && !mindfulTick) mindfulTick = setInterval(function () { renderTodayPanel(); if (state.filter === "mindfulness") renderContent(); }, 15000); if (!shouldRun && mindfulTick) { clearInterval(mindfulTick); mindfulTick = null; } }
    function formatDuration(seconds) { seconds = Math.max(0, Math.round(Number(seconds || 0))); var m = Math.floor(seconds / 60); var s = seconds % 60; if (m >= 60) { var h = Math.floor(m / 60); var mm = m % 60; return h + ':' + String(mm).padStart(2, '0') + ':' + String(s).padStart(2, '0'); } return m + ':' + String(s).padStart(2, '0'); }
    function formatMinutes(minutes) { var value = Math.round(Number(minutes || 0) * 100) / 100; return value + ' min'; }
    function shortClock(value) { try { return new Intl.DateTimeFormat("zh-CN", { timeZone: "Asia/Shanghai", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value)); } catch (_) { return String(value || "").slice(11, 16); } }
    function renderTrendPanel() { ensureTrendDefaults(); var defs = sortPinnedFirst(editableDefs()); var selected = findDef(state.trend.metric) || defs[0]; var data = state.trend.data && state.trend.data.metric_key === state.trend.metric ? state.trend.data : null; var html = '<div class="trend-panel"><section class="trend-card"><div class="trend-controls"><select id="trendMetric">' + defs.map(function (def) { return '<option value="' + escapeAttr(def.metric_key) + '">' + escapeHtml((state.pinned.indexOf(def.metric_key) !== -1 ? "★ " : "") + cleanLabel(def)) + '</option>'; }).join("") + '</select><div class="range-tabs">' + [30, 90, 180, 365].map(function (days) { return '<button type="button" data-trend-days="' + days + '" class="' + (Number(state.trend.days) === days ? 'active' : '') + '">' + days + '天</button>'; }).join("") + '</div></div></section>'; if (state.trend.loading) return html + '<div class="empty">正在读取历史数据…</div></div>'; if (!data) return html + '<div class="empty">选择字段后查看历史趋势。</div></div>'; html += '<section class="trend-card"><div class="section-head"><h2>' + escapeHtml(cleanLabel(selected || data.definition)) + '</h2><span>' + escapeHtml(data.start_date + " 到 " + data.end_date) + '</span></div>' + renderTrendStats(data) + '<div class="chart-wrap">' + renderTrendChart(data) + '</div></section>'; html += '<section class="trend-card"><div class="section-head"><h2>记录密度</h2><span>' + escapeHtml(data.stats.count + "/" + data.stats.day_count + " 天") + '</span></div>' + renderHistoryGrid(data) + '</section>'; html += '<section class="trend-card"><div class="section-head"><h2>最近记录</h2><span>最多 14 条</span></div>' + renderHistoryRows(data) + '</section></div>'; return html; }
    function renderBackfillPanel() { var daily = sortPinnedFirst(editableDefs()); return '<section class="backfill ' + (state.backfillOpen ? 'open' : '') + '"><h2>稳定值补录</h2><div class="backfill-result">适合药物、补剂、习惯这类“连续很多天一样，但中间漏记”的字段。先查缺口，再只补空白天，不覆盖已有记录。</div><div class="backfill-grid"><select id="backfillMetric">' + daily.map(function (def) { return '<option value="' + escapeAttr(def.metric_key) + '">' + escapeHtml((state.pinned.indexOf(def.metric_key) !== -1 ? "★ " : "") + cleanLabel(def)) + '</option>'; }).join("") + '</select><input id="backfillValue" placeholder="稳定值，例如 40 或 true"></div><div class="backfill-grid two"><input id="backfillStart" type="date"><input id="backfillEnd" type="date"></div><div id="backfillResult" class="backfill-result"></div><div class="backfill-actions"><button id="previewBackfill" type="button">查缺口</button><button id="runBackfill" class="primary" type="button">补空白天</button></div></section>'; }
    function fillBackfillControls() { if (!state.backfillOpen) return; var metric = document.getElementById("backfillMetric"); var value = document.getElementById("backfillValue"); var start = document.getElementById("backfillStart"); var end = document.getElementById("backfillEnd"); var result = document.getElementById("backfillResult"); if (!metric) return; if (!state.backfill.metric) state.backfill.metric = findDef("atomoxetine_total_mg") ? "atomoxetine_total_mg" : (state.pinned[0] || ""); if (!state.backfill.end) state.backfill.end = state.date || shanghaiDate(0); if (!state.backfill.start) state.backfill.start = addDays(state.backfill.end, -119); metric.value = state.backfill.metric; value.value = state.backfill.value; start.value = state.backfill.start; end.value = state.backfill.end; result.innerHTML = state.backfillPreview ? backfillPreviewText(state.backfillPreview) : "先选字段并查缺口。我会找最近一次记录，建议从它后一天开始补。"; }
    function ensureTrendDefaults() { var defs = sortPinnedFirst(editableDefs()); var preferred = ["atomoxetine_total_mg", "main_sleep_hours", "body_weight_clothed_jin", "blood_glucose_yuyue550"]; if (!state.trend.metric || !findDef(state.trend.metric)) { var found = preferred.map(findDef).filter(Boolean)[0] || defs[0]; state.trend.metric = (found || {}).metric_key || ""; } if (!state.trend.days) state.trend.days = 90; }
    function fillTrendControls() { ensureTrendDefaults(); var metric = document.getElementById("trendMetric"); if (metric) metric.value = state.trend.metric; }
    function trendTitle() { var def = findDef(state.trend.metric); return def ? cleanLabel(def) : "选择字段"; }
    async function loadTrend() { ensureTrendDefaults(); if (!state.trend.metric) return; var seq = ++trendLoadSeq; var metric = state.trend.metric; var days = Number(state.trend.days || 90); var date = state.date; var cacheKey = trendCacheKey(metric, days, date); var cached = readJson(cacheKey); if (cached && cached.data && cached.data.metric_key === metric && !state.trend.data) { state.trend.data = cached.data; renderAll(); } state.trend.loading = true; renderAll(); try { var data = await api("/api/history?metric_key=" + encodeURIComponent(metric) + "&days=" + encodeURIComponent(days) + "&end_date=" + encodeURIComponent(date)); if (seq !== trendLoadSeq || state.trend.metric !== metric || Number(state.trend.days) !== days || state.date !== date) return; state.trend.data = data; localStorage.setItem(cacheKey, JSON.stringify({ cached_at: new Date().toISOString(), data: data })); setStatus("已读取"); } catch (err) { if (seq === trendLoadSeq) showToast("历史读取失败"); } finally { if (seq === trendLoadSeq) { state.trend.loading = false; renderAll(); } } }
    function trendCacheKey(metric, days, date) { return "metricsPwaHistory:" + metric + ":" + days + ":" + date; }
    function renderTrendStats(data) { var def = data.definition || findDef(data.metric_key) || {}; var stats = data.stats || {}; var cells = []; cells.push(["最近", displayValue(stats.last_value, def)]); if (def.value_type === "number") { cells.push(["均值", stats.avg == null ? "空" : displayValue(stats.avg, def)]); cells.push(["最低/最高", (stats.min == null ? "空" : stats.min) + " / " + (stats.max == null ? "空" : stats.max)]); cells.push(["变化", stats.delta == null ? "空" : displayValue(stats.delta, def)]); } else if (def.value_type === "boolean") { cells.push(["是/否", (stats.true_count || 0) + " / " + (stats.false_count || 0)]); cells.push(["覆盖", stats.count + "/" + stats.day_count + " 天"]); cells.push(["缺失", stats.missing_count + " 天"]); } else { cells.push(["记录数", stats.count + " 条"]); cells.push(["覆盖", stats.count + "/" + stats.day_count + " 天"]); cells.push(["缺失", stats.missing_count + " 天"]); } return '<div class="trend-stats">' + cells.map(function (cell) { return '<div class="trend-stat"><b>' + escapeHtml(cell[1]) + '</b><span>' + escapeHtml(cell[0]) + '</span></div>'; }).join("") + '</div>'; }
    function renderTrendChart(data) { var def = data.definition || {}; if (def.value_type !== "number") return renderBoolTimeline(data); var rows = (data.rows || []).filter(function (row) { return typeof row.value === "number"; }); if (rows.length < 2) return '<div class="chart-empty">数值记录不足，至少 2 条后才能画趋势。</div>'; var values = rows.map(function (row) { return row.value; }); var min = Math.min.apply(null, values); var max = Math.max.apply(null, values); if (min === max) { min -= 1; max += 1; } var w = 640, h = 220, pad = 28; var points = rows.map(function (row, index) { var x = pad + (w - pad * 2) * (rows.length === 1 ? 0 : index / (rows.length - 1)); var y = h - pad - (h - pad * 2) * ((row.value - min) / (max - min)); return roundNumber(x) + "," + roundNumber(y); }).join(" "); var last = rows[rows.length - 1]; return '<svg class="chart" viewBox="0 0 ' + w + ' ' + h + '" preserveAspectRatio="none" role="img" aria-label="趋势图"><line x1="' + pad + '" y1="' + (h - pad) + '" x2="' + (w - pad) + '" y2="' + (h - pad) + '" stroke="#d7dde5" stroke-width="2"/><line x1="' + pad + '" y1="' + pad + '" x2="' + (w - pad) + '" y2="' + pad + '" stroke="#eef2f6" stroke-width="2"/><polyline points="' + points + '" fill="none" stroke="#0f766e" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><circle cx="' + points.split(" ").pop().split(",")[0] + '" cy="' + points.split(" ").pop().split(",")[1] + '" r="7" fill="#0f766e"/><text x="' + pad + '" y="20" fill="#667085" font-size="18">' + escapeHtml(String(max)) + '</text><text x="' + pad + '" y="' + (h - 6) + '" fill="#667085" font-size="18">' + escapeHtml(String(min)) + '</text><text x="' + (w - pad - 120) + '" y="24" fill="#111827" font-size="18">' + escapeHtml(shortDate(last.local_date) + " " + displayValue(last.value, def)) + '</text></svg>'; }
    function renderBoolTimeline(data) { var rows = data.rows || []; if (!rows.length) return '<div class="chart-empty">这个范围内没有记录。</div>'; var def = data.definition || {}; return '<div class="history-list">' + rows.slice(-8).reverse().map(function (row) { return '<div class="history-row"><div class="date">' + escapeHtml(row.local_date) + '</div><div class="value">' + escapeHtml(displayValue(row.value, def)) + '</div><div class="source">' + escapeHtml(row.source || "") + '</div></div>'; }).join("") + '</div>'; }
    function renderHistoryGrid(data) { var dates = enumerateDateStrings(data.start_date, data.end_date); var byDate = {}; (data.rows || []).forEach(function (row) { byDate[row.local_date] = row; }); var numeric = (data.rows || []).map(function (row) { return Number(row.value); }).filter(function (value) { return Number.isFinite(value); }); var min = numeric.length ? Math.min.apply(null, numeric) : 0; var max = numeric.length ? Math.max.apply(null, numeric) : 1; return '<div class="history-grid">' + dates.map(function (date) { var row = byDate[date]; var cls = 'history-cell'; if (row) { cls += ' has'; if (typeof row.value === "number" && max > min) { var ratio = (row.value - min) / (max - min); cls += ratio < .34 ? ' low' : ratio < .67 ? ' mid' : ''; } } return '<span class="' + cls + '" title="' + escapeAttr(date + (row ? ' ' + displayValue(row.value, data.definition) : ' 空')) + '"></span>'; }).join("") + '</div>'; }
    function renderHistoryRows(data) { var def = data.definition || {}; var rows = (data.rows || []).slice(-14).reverse(); if (!rows.length) return '<div class="empty">这个范围内没有记录。</div>'; return '<div class="history-list">' + rows.map(function (row) { return '<div class="history-row"><div class="date">' + escapeHtml(row.local_date) + '</div><div class="value">' + escapeHtml(displayValue(row.value, def)) + '</div><div class="source">' + escapeHtml(row.source || "") + '</div></div>'; }).join("") + '</div>'; }
    function renderDenseFilled(defs) { return '<div class="dense-list">' + defs.map(function (def) { var value = valueFor(def); var expanded = !!state.expanded[def.metric_key]; var pinned = state.pinned.indexOf(def.metric_key) !== -1; return '<article class="dense-row ' + (expanded ? 'expanded' : '') + '" data-metric="' + escapeAttr(def.metric_key) + '"><button class="star ' + (pinned ? 'on' : '') + '" type="button" data-pin="' + escapeAttr(def.metric_key) + '">★</button><div><div class="dense-label">' + escapeHtml(cleanLabel(def)) + '</div><div class="dense-sub">' + escapeHtml((CATEGORY_NAMES[def.category] || def.category || '其他') + (def.unit ? ' · ' + def.unit : '')) + '</div></div><div class="dense-value">' + escapeHtml(displayValue(value, def)) + '</div><button class="icon" type="button" data-info="' + escapeAttr(def.metric_key) + '">i</button>' + renderMetricDetail(def) + '</article>'; }).join("") + '</div>'; }
    function renderMetric(def) { var value = valueFor(def); var dirty = Object.prototype.hasOwnProperty.call(state.dirty, def.metric_key); var expanded = !!state.expanded[def.metric_key]; var pinned = state.pinned.indexOf(def.metric_key) !== -1; return '<article class="metric ' + (dirty ? 'dirty ' : '') + (expanded ? 'expanded' : '') + '" data-metric="' + escapeAttr(def.metric_key) + '"><div class="metric-main"><div class="metric-title-row"><button class="star ' + (pinned ? 'on' : '') + '" type="button" data-pin="' + escapeAttr(def.metric_key) + '" aria-label="常用">★</button><div><div class="metric-name">' + escapeHtml(cleanLabel(def)) + '</div><div class="metric-desc">' + escapeHtml(compactMeta(def)) + '</div></div><button class="icon" type="button" data-info="' + escapeAttr(def.metric_key) + '" aria-label="字段说明">i</button></div>' + renderMetricContext(def, value) + '</div><div class="metric-control">' + renderControl(def, value) + '</div>' + renderMetricDetail(def) + '</article>'; }
    function renderControl(def, value) { if (def.value_type === "boolean") return renderBool(def, value); if (def.value_type === "text") return '<input class="metric-input" data-key="' + escapeAttr(def.metric_key) + '" value="' + escapeAttr(value == null ? "" : value) + '" placeholder="输入文本">'; if (def.value_type === "number") return renderNumber(def, value); return '<button type="button" data-json="' + escapeAttr(def.metric_key) + '">用文本备注</button>'; }
    function renderNumber(def, value) { var step = stepFor(def); return '<div class="number-control"><button type="button" data-step="' + escapeAttr(def.metric_key) + '" data-delta="-' + step + '">−</button><input class="metric-input" data-key="' + escapeAttr(def.metric_key) + '" type="number" inputmode="decimal" step="' + step + '" value="' + escapeAttr(value == null ? "" : value) + '"><button type="button" data-step="' + escapeAttr(def.metric_key) + '" data-delta="' + step + '">+</button></div>'; }
    function renderBool(def, value) { var current = value === true ? "true" : value === false ? "false" : ""; return '<div class="tri"><button type="button" data-bool="' + escapeAttr(def.metric_key) + '" data-value="" class="' + (current === "" ? "active" : "") + '">—</button><button type="button" data-bool="' + escapeAttr(def.metric_key) + '" data-value="false" class="' + (current === "false" ? "active" : "") + '">否</button><button type="button" data-bool="' + escapeAttr(def.metric_key) + '" data-value="true" class="' + (current === "true" ? "active" : "") + '">是</button></div>'; }
    function renderMetricContext(def, value) { if (hasValueFor(def)) return '<div class="metric-context"><div class="context-text">今日：<strong>' + escapeHtml(displayValue(value, def)) + '</strong></div></div>'; var latest = latestFor(def); if (latest) return '<div class="metric-context"><div class="context-text">上次 ' + escapeHtml(shortDate(latest.local_date)) + '：<strong>' + escapeHtml(displayValue(latest.value, def)) + '</strong></div><button class="tiny accent" type="button" data-use-latest="' + escapeAttr(def.metric_key) + '">沿用</button></div>'; return '<div class="metric-context"><div class="context-text">暂无历史值，手动填一次后以后可沿用。</div></div>'; }
    function renderMetricDetail(def) { var lines = []; lines.push('<div><strong>说明：</strong>' + escapeHtml(def.description || '数据库暂无说明') + '</div>'); lines.push('<div><strong>字段：</strong><code>' + escapeHtml(def.metric_key) + '</code></div>'); lines.push('<div><strong>格式：</strong>' + escapeHtml(def.value_type + (def.unit ? ' · ' + def.unit : '') + ' · ' + (CATEGORY_NAMES[def.category] || def.category || '其他')) + '</div>'); if (def.aliases && def.aliases.length) lines.push('<div><strong>别名：</strong>' + escapeHtml(def.aliases.join(' / ')) + '</div>'); if (def.source_headers && def.source_headers.length) lines.push('<div><strong>原表头：</strong>' + escapeHtml(def.source_headers.join(' / ')) + '</div>'); if (def.aggregation_method) lines.push('<div><strong>聚合：</strong>' + escapeHtml(def.aggregation_method) + '</div>'); var md = def.metadata || {}; if (md.note) lines.push('<div><strong>写入备注：</strong>' + escapeHtml(String(md.note)) + '</div>'); if (md.write_kind || md.write_action || md.source_column) lines.push('<div><strong>元数据：</strong>' + escapeHtml([md.write_kind, md.write_action, md.source_column && '列 ' + md.source_column].filter(Boolean).join(' · ')) + '</div>'); if (md.write_format) lines.push('<div><strong>写入样例：</strong><pre>' + escapeHtml(JSON.stringify(md.write_format, null, 2)) + '</pre></div>'); return '<div class="metric-detail"><div class="detail-grid">' + lines.join("") + '</div></div>'; }
    function handleInput(event) { if (event.target && event.target.id === "backfillValue") { state.backfill.value = event.target.value; return; } var input = event.target.closest(".metric-input"); if (!input) return; var key = input.dataset.key; var def = findDef(key); if (!def) return; var value = input.value; if (value === "") setDirty(key, null); else if (def.value_type === "number") setDirty(key, Number(value)); else setDirty(key, value); }
    function handleChange(event) { if (!event.target) return; if (event.target.id === "trendMetric") { state.trend.metric = event.target.value; state.trend.data = null; localStorage.setItem("metricsPwaTrendMetric", state.trend.metric); renderAll(); loadTrend(); } if (event.target.id === "backfillMetric") { state.backfill.metric = event.target.value; state.backfillPreview = null; state.backfillTouchedStart = false; } if (event.target.id === "backfillValue") state.backfill.value = event.target.value; if (event.target.id === "backfillStart") { state.backfill.start = event.target.value; state.backfillTouchedStart = true; } if (event.target.id === "backfillEnd") state.backfill.end = event.target.value; }
    function handleMindfulScreenTap(event) { if (!isMindfulActiveView()) return; if (event.target.closest("[data-mindful-end-hold]")) { event.preventDefault(); event.stopPropagation(); if (!state.mindfulAction) showToast("结束需要长按"); return; } event.preventDefault(); event.stopPropagation(); var now = Date.now(); if (now - mindfulReturnClickAt < 350) return; mindfulReturnClickAt = now; runMindfulAction("return"); }
    function handleMindfulEndHoldStart(event) { if (!isMindfulActiveView()) return; var button = event.target.closest("[data-mindful-end-hold]"); if (!button || state.mindfulAction) return; event.preventDefault(); event.stopPropagation(); clearMindfulEndHold(); button.classList.add("holding"); mindfulEndHoldTimer = setTimeout(function () { mindfulEndHoldTimer = null; button.classList.remove("holding"); if (navigator.vibrate) navigator.vibrate(35); runMindfulAction("end"); }, 1300); }
    function clearMindfulEndHold() { if (mindfulEndHoldTimer) { clearTimeout(mindfulEndHoldTimer); mindfulEndHoldTimer = null; } var button = document.querySelector("[data-mindful-end-hold].holding"); if (button) button.classList.remove("holding"); }
    function handleClick(event) { var mindful = event.target.closest("[data-mindful-action]"); if (mindful) { runMindfulAction(mindful.dataset.mindfulAction); return; } var trendDays = event.target.closest("[data-trend-days]"); if (trendDays) { state.trend.days = Number(trendDays.dataset.trendDays || 90); state.trend.data = null; localStorage.setItem("metricsPwaTrendDays", String(state.trend.days)); renderAll(); loadTrend(); return; } var pin = event.target.closest("[data-pin]"); if (pin) { togglePinned(pin.dataset.pin); return; } var useLatest = event.target.closest("[data-use-latest]"); if (useLatest) { applyLatest(useLatest.dataset.useLatest); return; } var info = event.target.closest("[data-info]"); if (info) { state.expanded[info.dataset.info] = !state.expanded[info.dataset.info]; renderAll(); return; } var step = event.target.closest("[data-step]"); if (step) { var key = step.dataset.step; var input = el.content.querySelector('input[data-key="' + cssEscape(key) + '"]'); var current = Number(input && input.value || 0); var next = roundNumber(current + Number(step.dataset.delta || 0)); if (input) input.value = String(next); setDirty(key, next); renderAll(); return; } var bool = event.target.closest("[data-bool]"); if (bool) { var raw = bool.dataset.value; var value = raw === "" ? null : raw === "true"; setDirty(bool.dataset.bool, value); renderAll(); return; } if (event.target.closest("#previewBackfill")) { previewBackfill(); return; } if (event.target.closest("#runBackfill")) { runBackfill(); return; } }
    function setDirty(key, value) { state.dirty[key] = value; setStatus("未保存"); renderTodayPanel(); renderFilters(); updateFooter(); }
    function undoDirty() { state.dirty = {}; renderAll(); setStatus("已读取"); showToast("已撤销未保存改动"); }
    function applyLatest(key) { var def = findDef(key); var latest = def && latestFor(def); if (!latest) return showToast("没有可沿用的历史值"); state.dirty[key] = latest.value; setStatus("未保存"); renderAll(); showToast("已沿用上次值"); }
    function useLatestForPinned() { var applied = 0; pinnedDefs().forEach(function (def) { var latest = latestFor(def); if (!hasValueFor(def) && latest) { state.dirty[def.metric_key] = latest.value; applied += 1; } }); if (!applied) return showToast("没有可沿用的常用项"); setStatus("未保存"); renderAll(); showToast("已沿用 " + applied + " 项，确认后保存"); }
    async function runMindfulAction(action) { if (state.mindfulAction) return; if (["start", "return", "end"].indexOf(action) === -1) return; state.mindfulAction = true; renderAll(); try { var data = await api("/api/mindfulness/" + action, { method: "POST", body: JSON.stringify({}) }); state.mindfulness = data.today || state.mindfulness; showToast(data.message || "正念已更新"); await loadDay(); } catch (err) { showToast(action === "return" || action === "end" ? "没有进行中的正念" : "正念记录失败"); } finally { state.mindfulAction = false; renderAll(); } }
    async function saveDirty() { var keys = Object.keys(state.dirty); if (!keys.length) return showToast("没有改动"); var body = { local_date: state.date, metrics: state.dirty }; var snapshot = Object.assign({}, state.dirty); state.dirty = {}; renderAll(); try { await sendOrQueue("/api/metrics", "POST", body); Object.keys(snapshot).forEach(function (key) { state.values[key] = snapshot[key]; }); showToast("已保存 " + keys.length + " 项"); await loadDay(); } catch (err) { showToast("已排队"); } }
    async function previewBackfill() { var metric = document.getElementById("backfillMetric").value; var start = document.getElementById("backfillStart").value; var end = document.getElementById("backfillEnd").value || state.date; state.backfill.metric = metric; state.backfill.start = start; state.backfill.end = end; state.backfill.value = document.getElementById("backfillValue").value; setStatus("查缺口"); var data = await api("/api/metric_gaps?metric_key=" + encodeURIComponent(metric) + "&start_date=" + encodeURIComponent(start) + "&end_date=" + encodeURIComponent(end)); state.backfillPreview = data; if (data.latest && !state.backfill.value) state.backfill.value = displayValue(data.latest.value, data.definition).replace(/ .*/, ""); if (data.latest && !state.backfillTouchedStart) { var suggested = addDays(data.latest.local_date, 1); if (suggested <= end) state.backfill.start = suggested; } renderAll(); setStatus("已预览"); }
    async function runBackfill() { var metric = document.getElementById("backfillMetric").value; var value = document.getElementById("backfillValue").value; var start = document.getElementById("backfillStart").value; var end = document.getElementById("backfillEnd").value || state.date; state.backfill = { metric: metric, value: value, start: start, end: end }; if (!metric || !value || !start || !end) return showToast("补录信息不完整"); var body = { metric_key: metric, value: castBackfillValue(metric, value), start_date: start, end_date: end, only_empty: true }; var result = await sendOrQueue("/api/backfill", "POST", body); showToast(result.queued ? "补录已排队" : "已补 " + result.inserted + " 天"); state.backfillPreview = null; await loadDay(); }
    function backfillPreviewText(data) { var latest = data.latest ? ('最近记录：' + data.latest.local_date + ' = ' + displayValue(data.latest.value, data.definition) + '<br>') : '最近没有找到记录<br>'; return latest + '范围：' + data.start_date + ' 到 ' + data.end_date + '<br>空白 ' + data.missing_count + ' 天，已有 ' + data.existing_count + ' 天。执行时只补空白，不覆盖已有记录。'; }
    function toggleBackfill() { state.backfillOpen = !state.backfillOpen; if (state.backfillOpen) { state.query = ""; el.searchInput.value = ""; var advanced = document.querySelector(".advanced-tools"); if (advanced) advanced.open = false; } renderAll(); if (state.backfillOpen) setTimeout(function () { var panel = document.querySelector(".backfill.open"); if (panel) panel.scrollIntoView({ block: "start", behavior: "smooth" }); }, 30); }
    function focusFirstMissing() { state.filter = "unfilled"; localStorage.setItem("metricsPwaFilter", state.filter); renderAll(); setTimeout(function () { var first = document.querySelector('.metric input, .metric button[data-bool]'); if (first) first.focus(); }, 30); }
    function updateFooter() { var dirtyCount = Object.keys(state.dirty).length; el.pending.textContent = state.queue.length ? "待同步 " + state.queue.length : "无待同步"; el.saveBtn.textContent = dirtyCount ? "保存 " + dirtyCount : "保存"; el.undoBtn.classList.toggle("hidden", !dirtyCount); el.dirtyLabel.textContent = dirtyCount ? "已改 " + dirtyCount + " 项" : "未修改"; }
    function visibleDefs() { var defs = editableDefs(); var q = state.query.toLowerCase(); if (q) return defs.filter(function (def) { return searchText(def).indexOf(q) !== -1; }); if (state.filter === "unfilled") return unfilledDefs(); if (state.filter === "pinned") return sortUnfilledFirst(pinnedDefs()); if (state.filter === "filled") return filledDefs(); if (state.filter.indexOf("cat:") === 0) return sortUnfilledFirst(defsForCategory(state.filter.slice(4))); return sortUnfilledFirst(defs); }
    function editableDefs() { return state.defs.filter(function (d) { return d.category !== "strength_event" && d.category !== "medicine_event"; }); }
    function pinnedDefs() { var byKey = {}; editableDefs().forEach(function (def) { byKey[def.metric_key] = def; }); return state.pinned.map(function (key) { return byKey[key]; }).filter(Boolean); }
    function unfilledDefs() { return pinnedDefs().filter(function (def) { return !hasValueFor(def); }); }
    function filledDefs() { return editableDefs().filter(hasValueFor); }
    function defsForCategory(cat) { return editableDefs().filter(function (d) { return (d.category || "general") === cat; }); }
    function categories() { var cats = unique(editableDefs().map(function (d) { return d.category || "general"; })); cats.sort(function (a, b) { return orderIndex(a) - orderIndex(b); }); return cats; }
    function scopeTitle() { if (state.query) return '搜索“' + state.query + '”'; if (state.filter === "unfilled") return "待填常用"; if (state.filter === "pinned") return "常用字段"; if (state.filter === "filled") return "已填写字段"; if (state.filter.indexOf("cat:") === 0) return CATEGORY_NAMES[state.filter.slice(4)] || state.filter.slice(4); return "全部字段"; }
    function helperText() { if (state.filter === "filled" && !state.query) return "紧凑查看已填"; if (state.filter === "unfilled") return "只显示常用未填"; return state.query ? "搜索覆盖全部字段" : "未填会排在前面"; }
    function togglePinned(key) { var index = state.pinned.indexOf(key); if (index === -1) state.pinned.unshift(key); else state.pinned.splice(index, 1); state.pinned = cleanPinnedKeys(state.pinned); savePinned(); renderAll(); savePreferences(); }
    function sortUnfilledFirst(defs) { return defs.slice().sort(function (a, b) { return Number(hasValueFor(a)) - Number(hasValueFor(b)); }); }
    function hasValueFor(def) { var value = valueFor(def); return !(value === null || value === undefined || value === ""); }
    function valueFor(def) { return Object.prototype.hasOwnProperty.call(state.dirty, def.metric_key) ? state.dirty[def.metric_key] : state.values[def.metric_key]; }
    function findDef(key) { return state.defs.find(function (d) { return d.metric_key === key; }); }
    function orderIndex(cat) { var index = CATEGORY_ORDER.indexOf(cat); return index === -1 ? 999 : index; }
    function unique(list) { return Array.from(new Set(list)); }
    function cleanLabel(def) { return String(def.label || def.metric_key).replace(/\n+/g, " ").replace(/\s+/g, " ").trim(); }
    function compactMeta(def) { return [CATEGORY_NAMES[def.category] || def.category || "其他", def.value_type, def.unit].filter(Boolean).join(" · "); }
    function latestFor(def) { return state.latest && state.latest[def.metric_key] ? state.latest[def.metric_key] : null; }
    function shortDate(date) { return String(date || "").slice(5); }
    function sortPinnedFirst(defs) { return defs.slice().sort(function (a, b) { var ap = state.pinned.indexOf(a.metric_key); var bp = state.pinned.indexOf(b.metric_key); ap = ap === -1 ? 9999 : ap; bp = bp === -1 ? 9999 : bp; return ap - bp || orderIndex(a.category) - orderIndex(b.category) || cleanLabel(a).localeCompare(cleanLabel(b)); }); }
    function shortDescription(def) { var text = def.description || (def.aliases && def.aliases.length ? "别名：" + def.aliases.join(" / ") : "点 i 查看字段格式"); return text.length > 86 ? text.slice(0, 84) + "…" : text; }
    function metaPills(def) { var out = []; out.push(def.value_type || "value"); if (def.unit) out.push(def.unit); out.push(CATEGORY_NAMES[def.category] || def.category || "其他"); if (def.metadata && def.metadata.source_column) out.push("列 " + def.metadata.source_column); return out; }
    function searchText(def) { return [def.metric_key, def.label, def.description, def.unit, def.category, (def.aliases || []).join(" "), (def.source_headers || []).join(" ")].join(" ").toLowerCase(); }
    function displayValue(value, def) { if (value === true) return "是"; if (value === false) return "否"; if (value === null || value === undefined || value === "") return "空"; if (typeof value === "object") return JSON.stringify(value); return String(value) + (def && def.unit ? " " + def.unit : ""); }
    function castBackfillValue(metricKey, raw) { var def = findDef(metricKey); if (!def) return raw; if (def.value_type === "number") return Number(raw); if (def.value_type === "boolean") return /^(true|yes|1|是)$/i.test(String(raw)); return raw; }
    function stepFor(def) { var key = def.metric_key; if (key.indexOf("weight") !== -1 || key.indexOf("glucose") !== -1) return 0.1; if (key.indexOf("hours") !== -1) return 0.5; if (key.indexOf("_g") !== -1) return 50; if (def.unit === "scoop") return 0.25; return 1; }
    function roundNumber(value) { return Math.round(value * 100) / 100; }
    function escapeHtml(value) { return String(value == null ? "" : value).replace(/[&<>"']/g, function (char) { return ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]; }); }
    function escapeAttr(value) { return escapeHtml(value); }
    function cssEscape(value) { if (window.CSS && CSS.escape) return CSS.escape(value); return String(value).replace(/[^a-zA-Z0-9_-]/g, "\\$&"); }
    boot();
  })();
