(function () {
    var BASE = "https://mumcofuervklloaotpih.supabase.co/functions/v1/metrics-pwa";
    var APP_VERSION = "0.20.8";
    var APP_RELEASE = "2026-06-28";
    var CATEGORY_NAMES = { body: "身体", health: "健康", mindfulness: "正念", medicine: "药物", supplement: "补剂", food: "食物", learning: "学习", media: "媒体", media_sleep: "媒体睡眠", mood_productivity: "心情效率", productivity: "效率", sleep: "睡眠", habit: "习惯", pet: "宠物", general: "其他" };
    var CATEGORY_ORDER = ["body", "health", "mindfulness", "sleep", "mood_productivity", "productivity", "medicine", "supplement", "food", "learning", "media", "media_sleep", "habit", "pet", "general"];
    var DEFAULT_PINNED = ["body_weight_clothed_jin", "blood_glucose_yuyue550", "blood_glucose_post_meal_hours", "atomoxetine_total_mg", "eggs_count", "daily_nuts_bag_count", "reading_or_audiobook", "learn_english_on_x", "watched_financial_news"];
    var state = { authed: false, date: shanghaiDate(0), defs: [], values: {}, latest: {}, events: [], dirty: {}, filter: localStorage.getItem("metricsPwaFilter") || "unfilled", recordFilter: localStorage.getItem("metricsPwaRecordFilter") || "unfilled", query: "", expanded: {}, pinned: loadPinned(), token: localStorage.getItem("metricsPwaToken") || "", queue: loadQueue(), mindfulness: null, mindfulLoading: false, mindfulAction: false, pendingMindfulReturns: loadMindfulReturnEvents(), inFlightMindfulReturns: [], syncingMindfulReturns: false, sheet: "", mindfulEditId: "", trend: { metric: localStorage.getItem("metricsPwaTrendMetric") || "", days: Number(localStorage.getItem("metricsPwaTrendDays") || 90), data: null, loading: false }, backfillOpen: false, backfillPreview: null, backfillTouchedStart: false, backfill: { metric: "", value: "", start: "", end: "" } };
    var el = { login: document.getElementById("login"), app: document.getElementById("app"), loginForm: document.getElementById("loginForm"), passphrase: document.getElementById("passphrase"), loginMsg: document.getElementById("loginMsg"), dateInput: document.getElementById("dateInput"), status: document.getElementById("status"), settingsBtn: document.getElementById("settingsBtn"), appSheet: document.getElementById("appSheet"), todayPanel: document.getElementById("todayPanel"), modeTabs: document.getElementById("modeTabs"), searchInput: document.getElementById("searchInput"), clearSearch: document.getElementById("clearSearch"), filters: document.getElementById("filters"), useLatestBtn: document.getElementById("useLatestBtn"), firstMissingBtn: document.getElementById("firstMissingBtn"), backfillToggle: document.getElementById("backfillToggle"), scopeLabel: document.getElementById("scopeLabel"), dirtyLabel: document.getElementById("dirtyLabel"), content: document.getElementById("content"), pending: document.getElementById("pending"), undoBtn: document.getElementById("undoBtn"), saveBtn: document.getElementById("saveBtn"), toast: document.getElementById("toast") };
    var trendLoadSeq = 0;
    var mindfulTick = null;
    var mindfulEndHoldTimer = null;
    var mindfulReturnClickAt = 0;
    var mindfulReturnSyncTimer = null;
    var mindfulReturnSyncPromise = null;
    var queueFlushPromise = null;
    var refreshingForUpdate = false;
    var dayWriteSeq = 0;
    normalizeStoredFilter();
    var launchIntent = readLaunchIntent();
    function normalizeStoredFilter() { if (["unfilled", "pinned", "filled"].indexOf(state.filter) !== -1) state.recordFilter = state.filter; if (["unfilled", "pinned", "filled", "mindfulness", "trend", "all"].indexOf(state.filter) === -1 && state.filter.indexOf("cat:") !== 0) state.filter = state.recordFilter || "unfilled"; }
    function readLaunchIntent() { var params = new URLSearchParams(window.location.search); var mode = params.get("mode") || ""; var mindful = params.get("mindful") || ""; if (["start", "return", "end"].indexOf(mindful) === -1) mindful = ""; if (mode === "mindfulness" || mindful) { state.filter = "mindfulness"; localStorage.setItem("metricsPwaFilter", state.filter); } if (mode || mindful) { history.replaceState(null, "", window.location.pathname + window.location.hash); } return { mindful: mindful }; }
    function shanghaiDate(offset) { var base = new Date(Date.now() + offset * 86400000); var parts = new Intl.DateTimeFormat("en-US", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(base); var out = {}; parts.forEach(function (part) { out[part.type] = part.value; }); return out.year + "-" + out.month + "-" + out.day; }
    function addDays(date, offset) { var parts = date.split("-").map(Number); var d = new Date(Date.UTC(parts[0], parts[1] - 1, parts[2] + offset)); return d.toISOString().slice(0, 10); }
    function enumerateDateStrings(start, end) { var out = []; var cursor = start; var guard = 0; while (cursor <= end && guard < 800) { out.push(cursor); cursor = addDays(cursor, 1); guard += 1; } return out; }
    function uid() { return "pwa-" + Date.now() + "-" + Math.random().toString(16).slice(2); }
    function showToast(text) { el.toast.textContent = text; el.toast.classList.add("show"); setTimeout(function () { el.toast.classList.remove("show"); }, 1800); }
    function setStatus(text) { el.status.textContent = text; }
    function loadQueue() { try { var raw = JSON.parse(localStorage.getItem("metricsPwaQueue") || "[]"); return Array.isArray(raw) ? raw.filter(function (item) { return item && item.id && item.path && item.method; }).map(function (item) { return Object.assign({}, item, { in_flight: false }); }) : []; } catch (_) { return []; } }
    function loadMindfulReturnEvents() { var raw = readJson("metricsPwaMindfulReturnEvents"); return Array.isArray(raw) ? raw.filter(function (event) { return event && event.id && event.occurred_at; }) : []; }
    function saveMindfulReturnEvents() { var seen = {}; var events = []; (state.pendingMindfulReturns || []).concat(state.inFlightMindfulReturns || []).forEach(function (event) { if (!event || !event.id || seen[event.id]) return; seen[event.id] = true; events.push(event); }); localStorage.setItem("metricsPwaMindfulReturnEvents", JSON.stringify(events)); updateFooter(); }
    function cleanPinnedKeys(keys) { var out = []; if (!Array.isArray(keys)) return out; keys.forEach(function (item) { var key = String(item || "").trim(); if (/^[a-z][a-z0-9_]*$/.test(key) && out.indexOf(key) === -1) out.push(key); }); return out; }
    function localPinnedValue() { try { var saved = JSON.parse(localStorage.getItem("metricsPwaPinnedKeys") || "null"); return Array.isArray(saved) ? cleanPinnedKeys(saved) : null; } catch (_) { return null; } }
    function loadPinned() { var saved = localPinnedValue(); return Array.isArray(saved) ? saved : DEFAULT_PINNED.slice(); }
    function savePinned() { localStorage.setItem("metricsPwaPinnedKeys", JSON.stringify(cleanPinnedKeys(state.pinned))); }
    function saveQueue() { localStorage.setItem("metricsPwaQueue", JSON.stringify(state.queue)); updateFooter(); }
    function enqueue(item, silent) { if (!state.queue.some(function (queued) { return queued.id === item.id; })) state.queue.push(Object.assign({}, item, { in_flight: false })); saveQueue(); if (!silent) showToast("已加入待同步"); }
    function queueInFlight(item) { state.queue.push(Object.assign({}, item, { in_flight: true })); saveQueue(); }
    function removeQueueItem(id) { state.queue = state.queue.filter(function (item) { return item.id !== id; }); saveQueue(); }
    function markQueueItemIdle(id) { state.queue = state.queue.map(function (item) { return item.id === id ? Object.assign({}, item, { in_flight: false }) : item; }); saveQueue(); }
    function cacheKeyForDay(date) { return "metricsPwaDay:" + date; }
    function cacheKeyForMindfulness(date) { return "metricsPwaMindfulness:" + date; }
    function overlayKeyForDay(date) { return "metricsPwaOverlay:" + date; }
    function saveSchemaCache(defs) { localStorage.setItem("metricsPwaSchema", JSON.stringify({ cached_at: new Date().toISOString(), definitions: defs })); }
    function saveDayCache(date, data) { localStorage.setItem(cacheKeyForDay(date), JSON.stringify({ cached_at: new Date().toISOString(), data: data })); }
    function saveMindfulnessCache(date, today) { if (date && today) localStorage.setItem(cacheKeyForMindfulness(date), JSON.stringify({ cached_at: new Date().toISOString(), today: today })); }
    function saveDayOverlay(date, metrics) { var overlay = readJson(overlayKeyForDay(date)) || { metrics: {} }; overlay.metrics = Object.assign({}, overlay.metrics || {}, metrics || {}); overlay.synced = false; overlay.updated_at = new Date().toISOString(); localStorage.setItem(overlayKeyForDay(date), JSON.stringify(overlay)); }
    function markDayOverlaySynced(date, metrics) { clearDayOverlayMetrics(date, metrics); }
    function clearDayOverlayMetrics(date, metrics) { var overlay = readJson(overlayKeyForDay(date)); if (!overlay || !overlay.metrics) return; Object.keys(metrics || overlay.metrics).forEach(function (key) { if (!metrics || JSON.stringify(overlay.metrics[key]) === JSON.stringify(metrics[key])) delete overlay.metrics[key]; }); if (!Object.keys(overlay.metrics).length) localStorage.removeItem(overlayKeyForDay(date)); else localStorage.setItem(overlayKeyForDay(date), JSON.stringify(Object.assign({}, overlay, { synced: false, updated_at: new Date().toISOString() }))); }
    function pendingDayPatch(date) { var overlay = readJson(overlayKeyForDay(date)); return overlay && overlay.synced === false && overlay.metrics ? overlay.metrics : {}; }
    function mergeDayOverlay(date, values) { var patch = pendingDayPatch(date); var base = Object.assign({}, values || {}); Object.keys(patch).forEach(function (key) { var value = patch[key]; if (value === null || value === undefined || value === "") delete base[key]; else base[key] = value; }); return base; }
    function applyDayPatch(values, metrics) { var next = Object.assign({}, values || {}); Object.keys(metrics || {}).forEach(function (key) { var value = metrics[key]; if (value === null || value === undefined || value === "") delete next[key]; else next[key] = value; }); return next; }
    function updateDayCacheWithConfirmedMetrics(date, metrics) { var cached = readJson(cacheKeyForDay(date)); var data = cached && cached.data ? cached.data : { values: {}, latest_values: {}, events: [] }; data.values = applyDayPatch(data.values || {}, metrics || {}); saveDayCache(date, data); }
    function readJson(key) { try { return JSON.parse(localStorage.getItem(key) || "null"); } catch (_) { return null; } }
    function hydrateFromCache() { var schema = readJson("metricsPwaSchema"); var day = readJson(cacheKeyForDay(state.date)); var mindful = readJson(cacheKeyForMindfulness(state.date)); var used = false; if (schema && Array.isArray(schema.definitions)) { state.defs = schema.definitions; used = true; } if (day && day.data) { state.values = mergeDayOverlay(state.date, day.data.values || {}); state.latest = day.data.latest_values || {}; state.events = day.data.events || []; used = true; } if (mindful && mindful.today) { state.mindfulness = mindful.today; used = true; } if (used) { renderAll(); setStatus("本地缓存"); } }
    async function api(path, options) { var opts = options || {}; opts.credentials = "same-origin"; opts.headers = Object.assign({ "content-type": "application/json" }, opts.headers || {}); if (state.token) opts.headers.Authorization = "Bearer " + state.token; var res = await fetch(BASE + path, opts); var data = await res.json().catch(function () { return {}; }); if (res.status === 401) { state.authed = false; state.token = ""; localStorage.removeItem("metricsPwaToken"); showLogin(); throw new Error("Unauthorized"); } if (!res.ok || data.ok === false) throw new Error(data.error || "请求失败"); return data; }
    async function sendOrQueue(path, method, body) { var item = { id: uid(), path: path, method: method, body: body, created_at: new Date().toISOString() }; if (!navigator.onLine) { enqueue(item); return { queued: true }; } queueInFlight(item); try { var data = await api(path, { method: method, body: JSON.stringify(body) }); removeQueueItem(item.id); return data; } catch (err) { if (String(err.message) === "Unauthorized") removeQueueItem(item.id); else markQueueItemIdle(item.id); throw err; } }
    async function flushQueue() { if (queueFlushPromise) return await queueFlushPromise; queueFlushPromise = (async function () { if (!state.queue.length || !navigator.onLine) { saveQueue(); return; } var next = []; for (var i = 0; i < state.queue.length; i += 1) { var item = state.queue[i]; if (item.in_flight) { next.push(item); continue; } try { await api(item.path, { method: item.method, body: JSON.stringify(item.body) }); if (item.path === "/api/metrics" && item.body && item.body.local_date && item.body.metrics) { dayWriteSeq += 1; updateDayCacheWithConfirmedMetrics(item.body.local_date, item.body.metrics); markDayOverlaySynced(item.body.local_date, item.body.metrics); } } catch (err) { next.push(Object.assign({}, item, { in_flight: false })); next = next.concat(state.queue.slice(i + 1)); break; } } state.queue = next; saveQueue(); if (!state.queue.length) { showToast("同步完成"); await loadDay(); } })(); try { return await queueFlushPromise; } finally { queueFlushPromise = null; } }
    async function loadPreferences() { if (localStorage.getItem("metricsPwaPinnedPending") === "1") { await savePreferences(); return; } var localPinned = localPinnedValue(); var localNeedsMigration = Array.isArray(localPinned) && localStorage.getItem("metricsPwaPinnedSynced") !== "1"; try { setStatus("读取收藏"); var data = await api("/api/preferences"); var prefs = data.preferences || {}; if (localNeedsMigration) { state.pinned = localPinned; savePinned(); await savePreferences(); setStatus("本地收藏已迁移"); return; } if (data.exists && Array.isArray(prefs.pinned_metric_keys)) { state.pinned = cleanPinnedKeys(prefs.pinned_metric_keys); savePinned(); localStorage.setItem("metricsPwaPinnedSynced", "1"); renderAll(); setStatus("收藏已同步"); return; } state.pinned = loadPinned(); savePinned(); await savePreferences(); setStatus("收藏已迁移"); } catch (err) { setStatus("本地收藏"); } }
    async function savePreferences() { savePinned(); localStorage.setItem("metricsPwaPinnedPending", "1"); if (!navigator.onLine) { setStatus("收藏待同步"); return; } try { await api("/api/preferences", { method: "POST", body: JSON.stringify({ pinned_metric_keys: cleanPinnedKeys(state.pinned) }) }); localStorage.removeItem("metricsPwaPinnedPending"); localStorage.setItem("metricsPwaPinnedSynced", "1"); setStatus("收藏已同步"); } catch (err) { if (String(err.message) === "Unauthorized") localStorage.removeItem("metricsPwaPinnedPending"); else setStatus("收藏待同步"); } }
    async function syncAll() { await flushQueue(); await flushMindfulReturns(); await syncPendingPreferences(); }
    async function syncPendingPreferences() { if (localStorage.getItem("metricsPwaPinnedPending") === "1") await savePreferences(); }
    function showLogin() { el.login.classList.remove("hidden"); el.app.classList.add("hidden"); setTimeout(function () { el.passphrase.focus(); }, 50); }
    function showApp() { el.login.classList.add("hidden"); el.app.classList.remove("hidden"); }
    async function boot() { registerSW(); saveQueue(); el.dateInput.value = state.date; bindEvents(); if (!state.token) { showLogin(); return; } showApp(); hydrateFromCache(); try { await api("/api/session"); state.authed = true; showApp(); hydrateFromCache(); renderAll(); loadSchema().catch(function (err) { console.error(err); }); loadPreferences().catch(function (err) { console.error(err); }); loadDay().catch(function (err) { console.error(err); }); syncAll().catch(function (err) { console.error(err); }); await handleLaunchIntent(); } catch (err) { console.error("metrics-pwa boot failed", err); if (!state.defs.length) showLogin(); } }
    function registerSW() { if ("serviceWorker" in navigator) { navigator.serviceWorker.addEventListener("controllerchange", function () { if (refreshingForUpdate) return; refreshingForUpdate = true; window.location.reload(); }); navigator.serviceWorker.register("/personal-metrics-pwa/sw.js", { scope: "/personal-metrics-pwa/" }).then(function (registration) { registration.update().catch(function () {}); }).catch(function () {}); } }
    function bindEvents() {
      el.loginForm.addEventListener("submit", async function (event) {
        event.preventDefault();
        el.loginMsg.textContent = "验证中";
        try {
          var result = await api("/api/login", { method: "POST", body: JSON.stringify({ passphrase: el.passphrase.value }) });
          state.token = result.token || "";
          if (state.token) localStorage.setItem("metricsPwaToken", state.token);
          el.passphrase.value = "";
          state.authed = true;
          showApp();
          hydrateFromCache();
          renderAll();
          loadSchema().catch(function (err) { console.error(err); });
          loadPreferences().catch(function (err) { console.error(err); });
          loadDay().catch(function (err) { console.error(err); });
          syncAll().catch(function (err) { console.error(err); });
          await handleLaunchIntent();
          el.loginMsg.textContent = "";
        } catch (err) {
          el.loginMsg.textContent = "口令不对或尝试过多";
        }
      });
      document.getElementById("todayBtn").addEventListener("click", function () { changeDate(shanghaiDate(0)); });
      document.getElementById("prevDay").addEventListener("click", function () { changeDate(addDays(state.date, -1)); });
      document.getElementById("nextDay").addEventListener("click", function () { changeDate(addDays(state.date, 1)); });
      el.dateInput.addEventListener("change", function () { changeDate(el.dateInput.value); });
      el.searchInput.addEventListener("input", function () { state.query = el.searchInput.value.trim(); renderAll(); });
      el.clearSearch.addEventListener("click", function () { el.searchInput.value = ""; state.query = ""; renderAll(); });
      el.saveBtn.addEventListener("click", saveDirty);
      document.getElementById("syncBtn").addEventListener("click", syncAll);
      el.undoBtn.addEventListener("click", undoDirty);
      el.useLatestBtn.addEventListener("click", useLatestForPinned);
      el.firstMissingBtn.addEventListener("click", focusFirstMissing);
      el.backfillToggle.addEventListener("click", toggleBackfill);
      el.settingsBtn.addEventListener("click", function () { state.sheet = "settings"; renderAll(); });
      el.appSheet.addEventListener("click", handleSheetClick);
      window.addEventListener("online", syncAll);
      el.modeTabs.addEventListener("click", handleFilterClick);
      el.filters.addEventListener("click", handleFilterClick);
      el.content.addEventListener("input", handleInput);
      el.content.addEventListener("change", handleChange);
      el.content.addEventListener("click", handleClick);
      el.app.addEventListener("pointerdown", handleMindfulPointerDown, true);
      el.app.addEventListener("pointerdown", handleMindfulEndHoldStart, true);
      el.app.addEventListener("pointerup", clearMindfulEndHold, true);
      el.app.addEventListener("pointercancel", clearMindfulEndHold, true);
      el.app.addEventListener("pointerleave", clearMindfulEndHold, true);
      el.app.addEventListener("contextmenu", handleMindfulContextMenu, true);
    }
    function handleFilterClick(event) { var section = event.target.closest("button[data-section]"); if (section) { selectSection(section.dataset.section); return; } var btn = event.target.closest("button[data-filter]"); if (!btn) return; state.filter = btn.dataset.filter; localStorage.setItem("metricsPwaFilter", state.filter); renderAll(); if (state.filter === "mindfulness") loadMindfulness(); if (state.filter === "trend") loadTrend(); }
    function selectSection(section) { if (section === "records") { state.filter = state.recordFilter || "unfilled"; } else if (section === "mindfulness") { state.filter = "mindfulness"; } else if (section === "trend") { state.filter = "trend"; } else if (section === "fields") { state.filter = "all"; } localStorage.setItem("metricsPwaFilter", state.filter); renderAll(); if (state.filter === "mindfulness") loadMindfulness(); if (state.filter === "trend") loadTrend(); }
    function selectRecordFilter(filter) { if (["unfilled", "pinned", "filled"].indexOf(filter) === -1) return; state.recordFilter = filter; state.filter = filter; localStorage.setItem("metricsPwaRecordFilter", filter); localStorage.setItem("metricsPwaFilter", filter); renderAll(); }
    async function changeDate(date) { state.date = date; el.dateInput.value = date; state.dirty = {}; var cached = readJson(cacheKeyForDay(date)); if (cached && cached.data) { state.values = mergeDayOverlay(date, cached.data.values || {}); state.latest = cached.data.latest_values || {}; state.events = cached.data.events || []; renderAll(); setStatus(Object.keys(pendingDayPatch(date)).length ? "本地缓存，有待同步" : "本地缓存"); } loadDay().catch(function (err) { console.error(err); }); }
    async function loadSchema() { setStatus("加载字段"); var data = await api("/api/schema"); state.defs = data.definitions || []; saveSchemaCache(state.defs); renderAll(); }
    async function loadDay() { var date = state.date; var readWriteSeq = dayWriteSeq; var cached = readJson(cacheKeyForDay(date)); if (cached && cached.data) { state.values = mergeDayOverlay(date, cached.data.values || {}); state.latest = cached.data.latest_values || {}; state.events = cached.data.events || []; renderAll(); setStatus(Object.keys(pendingDayPatch(date)).length ? "本地缓存，有待同步" : "本地缓存，后台同步"); } try { setStatus(cached ? "后台同步" : "读取中"); var data = await api("/api/day?date=" + encodeURIComponent(date)); if (state.date !== date || dayWriteSeq !== readWriteSeq) return; state.values = mergeDayOverlay(date, data.values || {}); state.latest = data.latest_values || {}; state.events = data.events || []; saveDayCache(date, data); renderAll(); setStatus(Object.keys(pendingDayPatch(date)).length ? "已读取，有本地待同步" : "已同步"); } catch (err) { setStatus(cached ? "离线缓存" : "读取失败"); if (!cached) showToast("读取失败"); } loadMindfulness().catch(function (err) { console.error(err); }); if (state.filter === "trend") loadTrend(); }
    async function loadMindfulness() { if (state.mindfulLoading) return; var date = state.date; var cached = readJson(cacheKeyForMindfulness(date)); if (cached && cached.today && (!state.mindfulness || state.mindfulness.local_date !== date)) { state.mindfulness = cached.today; renderAll(); setStatus("正念本地缓存"); if (state.pendingMindfulReturns.length && mindfulActive()) scheduleMindfulReturnFlush(300); } else if (state.mindfulness && state.mindfulness.local_date !== date) { state.mindfulness = null; renderAll(); } state.mindfulLoading = true; try { var data = await api("/api/mindfulness/today?date=" + encodeURIComponent(date)); if (state.date !== date) return; var incoming = data.today || null; if (mindfulActive() && (!incoming || !incoming.active_session) && state.mindfulAction) return; if (mindfulActive() && mindfulActive().metadata && mindfulActive().metadata.optimistic && (!incoming || !incoming.active_session)) return; state.mindfulness = incoming; saveMindfulnessCache(date, state.mindfulness); if (state.pendingMindfulReturns.length && mindfulActive()) scheduleMindfulReturnFlush(40); } catch (err) { if (!cached) setStatus("正念读取失败"); } finally { state.mindfulLoading = false; renderAll(); } }
    async function handleLaunchIntent() { if (state.filter !== "mindfulness" && !launchIntent.mindful) return; state.filter = "mindfulness"; localStorage.setItem("metricsPwaFilter", state.filter); renderAll(); await loadMindfulness(); if (!launchIntent.mindful) return; var action = launchIntent.mindful; launchIntent.mindful = ""; await runMindfulAction(action); }
    function renderAll() { renderTodayPanel(); renderFilters(); renderContent(); renderAppSheet(); updateFooter(); manageMindfulTimer(); updateMindfulActiveMode(); }
    function renderTodayPanel() { var section = appSection(); if (section === "mindfulness") { var totals = mindfulTotals(); el.todayPanel.innerHTML = '<div class="today-top"><div><div class="today-title">正念练习</div><div class="today-sub">' + escapeHtml(state.date) + ' · 今日 ' + escapeHtml(formatMinutes(totals.minutes)) + ' · 拉回 ' + escapeHtml(String(totals.returns)) + '</div></div><div class="stat"><b>' + escapeHtml(String(totals.sessions)) + '</b><span>会话</span></div></div><div class="stats"><div class="stat"><b>' + escapeHtml(formatMinutes(totals.minutes)) + '</b><span>今日时长</span></div><div class="stat"><b>' + escapeHtml(String(totals.returns)) + '</b><span>今日拉回</span></div><div class="stat"><b>' + escapeHtml(totals.density == null ? '—' : String(totals.density)) + '</b><span>密度</span></div></div>'; el.useLatestBtn.disabled = true; return; } if (section === "trend") { el.todayPanel.innerHTML = '<div class="today-top"><div><div class="today-title">趋势与历史</div><div class="today-sub">' + escapeHtml(trendTitle()) + ' · ' + escapeHtml(String(state.trend.days || 90)) + ' 天 · 先看缓存再刷新</div></div><div class="stat"><b>' + escapeHtml(String(editableDefs().length)) + '</b><span>字段</span></div></div>'; el.useLatestBtn.disabled = true; return; } if (section === "fields") { el.todayPanel.innerHTML = '<div class="today-top"><div><div class="today-title">字段库</div><div class="today-sub">' + escapeHtml(state.date) + ' · 搜索字段、格式、写入说明和分类</div></div><div class="stat"><b>' + escapeHtml(String(editableDefs().length)) + '</b><span>字段</span></div></div>'; el.useLatestBtn.disabled = true; return; } var pinned = pinnedDefs(); var filled = pinned.filter(hasValueFor).length; var total = pinned.length || 1; var missing = Math.max(total - filled, 0); var dirtyCount = logicalDirtyCount(); var pct = Math.round(filled / total * 100); var latestUsable = pinned.filter(function (def) { return !hasValueFor(def) && latestFor(def); }).length; el.todayPanel.innerHTML = '<div class="today-top"><div><div class="today-title">今天还差 ' + missing + ' 项</div><div class="today-sub">' + escapeHtml(state.date) + ' · 常用 ' + filled + '/' + total + ' · ' + (latestUsable ? latestUsable + ' 项可沿用上次值' : '没有可直接沿用的常用项') + '</div></div><div class="stat"><b>' + pct + '%</b><span>完成</span></div></div><div class="progress-track"><div class="progress-fill" style="width:' + pct + '%"></div></div><div class="stats"><div class="stat"><b>' + filled + '</b><span>常用已填</span></div><div class="stat"><b>' + missing + '</b><span>常用待填</span></div><div class="stat"><b>' + dirtyCount + '</b><span>未保存</span></div></div>'; el.useLatestBtn.disabled = latestUsable === 0; }
    function renderFilters() { var section = appSection(); var modes = [{ key: "records", name: "记录", count: unfilledDefs().length }, { key: "mindfulness", name: "正念", count: "" }, { key: "trend", name: "趋势", count: "" }, { key: "fields", name: "字段", count: editableDefs().length }]; el.modeTabs.innerHTML = modes.map(function (chip) { return '<button type="button" data-section="' + escapeAttr(chip.key) + '" class="' + (section === chip.key ? 'active' : '') + '">' + escapeHtml(chip.name + (chip.count !== "" ? " " + chip.count : "")) + '</button>'; }).join(""); var cats = section === "fields" ? categories() : []; el.filters.innerHTML = cats.map(function (cat) { var key = "cat:" + cat; return '<button type="button" data-filter="' + escapeAttr(key) + '" class="' + (state.filter === key ? 'active' : '') + '">' + escapeHtml(CATEGORY_NAMES[cat] || cat) + ' ' + defsForCategory(cat).length + '</button>'; }).join(""); el.clearSearch.classList.toggle("hidden", !state.query); var quick = document.querySelector(".quick-actions"); if (quick) quick.classList.toggle("hidden", section !== "records"); var advanced = document.querySelector(".advanced-tools"); if (advanced) advanced.classList.toggle("hidden", section === "mindfulness" || section === "trend"); }
    function renderContent() { var section = appSection(); if (section === "mindfulness") { el.content.innerHTML = renderMindfulnessPanel(); el.scopeLabel.textContent = "正念 · 今日"; return; } if (section === "trend") { el.content.innerHTML = renderTrendPanel(); el.scopeLabel.textContent = "趋势 · " + trendTitle(); fillTrendControls(); return; } var defs = visibleDefs(); var title = scopeTitle(); var dirtyCount = logicalDirtyCount(); var html = section === "records" ? renderRecordTabs() + renderBackfillPanel() : ""; html += '<div class="section-head"><h2>' + escapeHtml(title) + '</h2><span>' + escapeHtml(helperText()) + '</span></div>'; if (!defs.length && dirtyCount && state.filter === "unfilled" && !state.query) html += '<div class="done-card"><b>待填常用已放进待保存清单</b><span>底部显示“保存 ' + dirtyCount + '”。你还可以切到“常用”逐项检查，或直接保存。</span></div>'; else if (!defs.length) html += '<div class="empty">没有匹配字段。可以搜索字段，或切到“字段”。</div>'; else if (state.filter === "filled" && !state.query) html += renderDenseFilled(defs); else html += '<div class="metric-list">' + defs.map(renderMetric).join("") + '</div>'; el.content.innerHTML = html; el.scopeLabel.textContent = title + ' · 显示 ' + defs.length + ' 项'; fillBackfillControls(); }
    function renderRecordTabs() { var tabs = [{ key: "unfilled", name: "待填", count: unfilledDefs().length }, { key: "pinned", name: "常用", count: pinnedDefs().length }, { key: "filled", name: "已填", count: filledDefs().length }]; return '<nav class="record-tabs" aria-label="记录筛选">' + tabs.map(function (tab) { return '<button type="button" data-record-filter="' + escapeAttr(tab.key) + '" class="' + (state.filter === tab.key ? 'active' : '') + '">' + escapeHtml(tab.name + ' ' + tab.count) + '</button>'; }).join("") + '</nav>'; }
    function renderAppSheet() { if (!el.appSheet) return; if (!state.sheet) { el.appSheet.classList.add("hidden"); el.appSheet.innerHTML = ""; return; } el.appSheet.classList.remove("hidden"); el.appSheet.innerHTML = state.sheet === "mindful-edit" ? renderMindfulEditSheet() : renderSettingsSheet(); }
    function renderSettingsSheet() { var dayCache = localCacheCount("metricsPwaDay:"); var historyCache = localCacheCount("metricsPwaHistory:"); var mindfulCache = localCacheCount("metricsPwaMindfulness:"); var overlayCache = localOverlayPendingCount(); return '<div class="sheet-card"><div class="sheet-head"><div><h2>设置与关于</h2><span>每日数据 v' + escapeHtml(APP_VERSION) + ' · ' + escapeHtml(APP_RELEASE) + '</span></div><button class="icon" type="button" data-sheet-action="close" aria-label="关闭">×</button></div><div class="sheet-body"><div class="sheet-row"><div><b>登录状态</b><span>只显示状态，不显示口令或令牌。</span></div><strong>' + escapeHtml(state.token ? "已登录" : "未登录") + '</strong></div><div class="sheet-row"><div><b>本地缓存</b><span>字段缓存、每日服务器快照、正念缓存、待同步字段和趋势缓存。</span></div><strong>' + dayCache + ' 天 / 待同步 ' + overlayCache + ' 天 / 正念 ' + mindfulCache + ' 天 / 历史 ' + historyCache + ' 条</strong></div><div class="sheet-row"><div><b>离线队列</b><span>断网时写入会先排队，联网后同步。</span></div><strong>' + escapeHtml(String(state.queue.length)) + '</strong></div><div class="sheet-actions"><button type="button" data-sheet-action="sync">立即同步</button><button type="button" data-sheet-action="clear-cache">清缓存</button><button type="button" data-sheet-action="reload">刷新版本</button><button class="danger" type="button" data-sheet-action="logout">退出登录</button></div></div></div>'; }
    function renderMindfulEditSheet() { var session = findMindfulSession(state.mindfulEditId); if (!session) return '<div class="sheet-card"><div class="sheet-head"><div><h2>编辑正念</h2><span>这条记录已经不在当前列表里。</span></div><button class="icon" type="button" data-sheet-action="close">×</button></div></div>'; var seconds = session.status === "active" ? activeMindfulSeconds() : Number(session.duration_seconds || 0); var minutes = Math.round(seconds / 60 * 100) / 100; return '<div class="sheet-card"><div class="sheet-head"><div><h2>编辑正念会话</h2><span>' + escapeHtml(shortClock(session.started_at) + ' · ' + (session.status === "active" ? "进行中" : "已结束")) + '</span></div><button class="icon" type="button" data-sheet-action="close" aria-label="关闭">×</button></div><div class="sheet-body"><div class="sheet-form"><label>时长（分钟）<input id="mindfulEditMinutes" type="number" inputmode="decimal" min="0" max="1440" step="0.1" value="' + escapeAttr(minutes) + '"></label><label>拉回次数<input id="mindfulEditReturns" type="number" inputmode="numeric" min="0" max="999" step="1" value="' + escapeAttr(session.return_count || 0) + '"></label><label>备注<textarea id="mindfulEditNote" placeholder="可选">' + escapeHtml(session.note || "") + '</textarea></label></div><div class="sheet-actions"><button type="button" data-sheet-action="close">取消</button><button class="primary" type="button" data-sheet-action="save-mindful">保存</button></div></div></div>'; }
    function localCacheCount(prefix) { var count = 0; for (var i = 0; i < localStorage.length; i += 1) if (String(localStorage.key(i) || "").indexOf(prefix) === 0) count += 1; return count; }
    function mindfulActive() { return state.mindfulness && state.mindfulness.active_session; }
    function isMindfulActiveView() { return state.filter === "mindfulness" && !!mindfulActive(); }
    function updateMindfulActiveMode() { document.body.classList.toggle("mindful-active-mode", isMindfulActiveView()); }
    function activeMindfulSeconds() { var active = mindfulActive(); if (!active || !active.started_at) return 0; return Math.max(0, Math.round((Date.now() - Date.parse(active.started_at)) / 1000)); }
    function mindfulLocalReturns() { return (state.pendingMindfulReturns || []).length + (state.inFlightMindfulReturns || []).length; }
    function mindfulSessionReturns() { var active = mindfulActive(); return Number((active && active.return_count) || 0) + mindfulLocalReturns(); }
    function mindfulTotals() { var today = state.mindfulness || {}; var summary = today.summary || {}; var completed = Number(summary.completed_seconds || 0); var activeSeconds = activeMindfulSeconds(); var total = completed + activeSeconds; var minutes = Math.round(total / 60 * 100) / 100; var dayReturns = Number(summary.return_count || 0) + mindfulLocalReturns(); var sessionReturns = mindfulSessionReturns(); var activeMinutes = Math.round(activeSeconds / 60 * 100) / 100; var densityBase = mindfulActive() ? activeMinutes : minutes; var densityReturns = mindfulActive() ? sessionReturns : dayReturns; return { sessions: Number(summary.session_count || 0), returns: dayReturns, session_returns: sessionReturns, total_seconds: total, minutes: minutes, density: densityBase > 0 ? Math.round(densityReturns / densityBase * 100) / 100 : null, active_seconds: activeSeconds, pending_returns: mindfulLocalReturns() }; }
    function renderMindfulnessPanel() { var totals = mindfulTotals(); var active = mindfulActive(); var sessions = (state.mindfulness && state.mindfulness.sessions) || []; if (active) return renderMindfulnessActivePanel(totals, sessions); var html = '<div class="mindful-panel"><section class="mindful-card"><div class="mindful-hero"><div class="mindful-state"><b>今天的正念</b><span>开始时点一次，结束时长按；练习中随意点屏幕就是一次拉回。</span></div><div class="mindful-timer"><b>' + escapeHtml(formatDuration(totals.total_seconds)) + '</b><span>今日</span></div></div><div class="mindful-actions"><button class="primary" type="button" data-mindful-action="start" ' + (state.mindfulAction ? 'disabled' : '') + '>开始正念</button></div><div class="mindful-stats"><div class="mindful-stat"><b>' + escapeHtml(String(totals.sessions)) + '</b><span>会话次数</span></div><div class="mindful-stat"><b>' + escapeHtml(formatMinutes(totals.minutes)) + '</b><span>总时长</span></div><div class="mindful-stat"><b>' + escapeHtml(String(totals.returns)) + '</b><span>拉回次数</span></div><div class="mindful-stat"><b>' + escapeHtml(totals.density == null ? '—' : String(totals.density)) + '</b><span>次/分钟</span></div></div><div class="mindful-note">拉回密度只能看趋势：下降可能是注意更稳，也可能是走神后没发现。这里不做 KPI，只帮你看见练习。</div></section>'; html += '<section class="mindful-card"><div class="section-head"><h2>今日会话</h2><span>' + escapeHtml(state.date) + '</span></div>' + renderMindfulSessions(sessions, true) + '</section></div>'; return html; }
    function renderMindfulnessActivePanel(totals, sessions) { var sync = totals.pending_returns ? '<small class="mindful-sync">待同步 ' + escapeHtml(String(totals.pending_returns)) + '</small>' : ''; return '<div class="mindful-active-screen"><section class="mindful-tap-zone" data-mindful-tap role="button" tabindex="0" aria-label="点任意位置记录一次拉回"><div class="mindful-active-top"><span>正念进行中</span><b>' + escapeHtml(formatDuration(totals.active_seconds || totals.total_seconds)) + '</b><small>闭眼时不用找按钮：点到屏幕任何位置，都会记一次拉回。</small></div><div class="mindful-active-count"><b>' + escapeHtml(String(totals.session_returns)) + '</b><span>本次拉回</span>' + sync + '</div><div class="mindful-active-grid"><div><b>' + escapeHtml(String(totals.returns)) + '</b><span>今日拉回</span></div><div><b>' + escapeHtml(formatMinutes(totals.minutes)) + '</b><span>今日总时长</span></div><div><b>' + escapeHtml(totals.density == null ? '—' : String(totals.density)) + '</b><span>本次/分钟</span></div></div></section><section class="mindful-end-zone"><button class="mindful-end-hold" type="button" data-mindful-end-hold ' + (state.mindfulAction ? 'disabled' : '') + '>长按结束</button><span>普通点击不会结束，也不会记拉回。按住到震动/提示后才结束。</span></section><section class="mindful-card mindful-active-history"><div class="section-head"><h2>今日会话</h2><span>' + escapeHtml(state.date) + '</span></div>' + renderMindfulSessions(sessions, false) + '</section></div>'; }
    function renderMindfulSessions(sessions, allowActions) { if (!sessions.length) return '<div class="empty">今天还没有正念会话。</div>'; return '<div class="history-list">' + sessions.slice(0, 8).map(function (session) { var seconds = session.status === "active" ? activeMindfulSeconds() : Number(session.duration_seconds || 0); var returns = Number(session.return_count || 0) + (session.status === "active" ? mindfulLocalReturns() : 0); var actions = allowActions ? '<div class="history-actions"><button class="tiny" type="button" data-mindful-edit="' + escapeAttr(session.id) + '">编辑</button><button class="tiny danger" type="button" data-mindful-delete="' + escapeAttr(session.id) + '">删除</button></div>' : ''; return '<div class="history-row ' + (allowActions ? 'has-actions' : '') + '"><div class="date">' + escapeHtml(shortClock(session.started_at)) + '</div><div class="value">' + escapeHtml(formatDuration(seconds) + ' · 拉回 ' + returns) + '</div><div class="source">' + escapeHtml(session.status === "active" ? "进行中" : "已结束") + '</div>' + actions + '</div>'; }).join("") + '</div>'; }
    function manageMindfulTimer() { var shouldRun = !!mindfulActive(); if (shouldRun && !mindfulTick) mindfulTick = setInterval(function () { renderTodayPanel(); if (state.filter === "mindfulness") renderContent(); }, 15000); if (!shouldRun && mindfulTick) { clearInterval(mindfulTick); mindfulTick = null; } }
    function formatDuration(seconds) { seconds = Math.max(0, Math.round(Number(seconds || 0))); var m = Math.floor(seconds / 60); var s = seconds % 60; if (m >= 60) { var h = Math.floor(m / 60); var mm = m % 60; return h + ':' + String(mm).padStart(2, '0') + ':' + String(s).padStart(2, '0'); } return m + ':' + String(s).padStart(2, '0'); }
    function formatMinutes(minutes) { var value = Math.round(Number(minutes || 0) * 100) / 100; return value + ' min'; }
    function shortClock(value) { try { return new Intl.DateTimeFormat("zh-CN", { timeZone: "Asia/Shanghai", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value)); } catch (_) { return String(value || "").slice(11, 16); } }
    function renderTrendPanel() { ensureTrendDefaults(); var defs = sortPinnedFirst(editableDefs()); var selected = findDef(state.trend.metric) || defs[0]; var data = state.trend.data && state.trend.data.metric_key === state.trend.metric ? state.trend.data : null; var html = '<div class="trend-panel"><section class="trend-card"><div class="trend-controls"><select id="trendMetric">' + defs.map(function (def) { return '<option value="' + escapeAttr(def.metric_key) + '">' + escapeHtml((state.pinned.indexOf(def.metric_key) !== -1 ? "★ " : "") + cleanLabel(def)) + '</option>'; }).join("") + '</select><div class="range-tabs">' + [30, 90, 180, 365].map(function (days) { return '<button type="button" data-trend-days="' + days + '" class="' + (Number(state.trend.days) === days ? 'active' : '') + '">' + days + '天</button>'; }).join("") + '</div></div></section>'; if (state.trend.loading) return html + '<div class="empty">正在读取历史数据…</div></div>'; if (!data) return html + '<div class="empty">选择字段后查看历史趋势。</div></div>'; html += '<section class="trend-card"><div class="section-head"><h2>' + escapeHtml(cleanLabel(selected || data.definition)) + '</h2><span>' + escapeHtml(data.start_date + " 到 " + data.end_date) + '</span></div>' + renderTrendStats(data) + '<div class="chart-wrap">' + renderTrendChart(data) + '</div></section>'; html += '<section class="trend-card"><div class="section-head"><h2>记录密度</h2><span>' + escapeHtml(data.stats.count + "/" + data.stats.day_count + " 天") + '</span></div>' + renderHistoryGrid(data) + '</section>'; html += '<section class="trend-card"><div class="section-head"><h2>最近记录</h2><span>最多 14 条</span></div>' + renderHistoryRows(data) + '</section></div>'; return html; }
    function renderBackfillPanel() { var daily = sortPinnedFirst(editableDefs()); return '<section class="backfill ' + (state.backfillOpen ? 'open' : '') + '"><h2>稳定值补录</h2><div class="backfill-result">适合药物、补剂、习惯这类“连续很多天一样，但中间漏记”的字段。先查缺口，再只补空白天，不覆盖已有记录。</div><div class="backfill-grid"><select id="backfillMetric">' + daily.map(function (def) { return '<option value="' + escapeAttr(def.metric_key) + '">' + escapeHtml((state.pinned.indexOf(def.metric_key) !== -1 ? "★ " : "") + cleanLabel(def)) + '</option>'; }).join("") + '</select><input id="backfillValue" placeholder="稳定值，例如 40 或 true"></div><div class="backfill-grid two"><input id="backfillStart" type="date"><input id="backfillEnd" type="date"></div><div id="backfillResult" class="backfill-result"></div><div class="backfill-actions"><button id="previewBackfill" type="button">查缺口</button><button id="runBackfill" class="primary" type="button">补空白天</button></div></section>'; }
    function fillBackfillControls() { if (!state.backfillOpen) return; var metric = document.getElementById("backfillMetric"); var value = document.getElementById("backfillValue"); var start = document.getElementById("backfillStart"); var end = document.getElementById("backfillEnd"); var result = document.getElementById("backfillResult"); if (!metric) return; if (!state.backfill.metric) state.backfill.metric = findDef("atomoxetine_total_mg") ? "atomoxetine_total_mg" : (state.pinned[0] || ""); if (!state.backfill.end) state.backfill.end = state.date || shanghaiDate(0); if (!state.backfill.start) state.backfill.start = addDays(state.backfill.end, -119); metric.value = state.backfill.metric; value.value = state.backfill.value; start.value = state.backfill.start; end.value = state.backfill.end; result.innerHTML = state.backfillPreview ? backfillPreviewText(state.backfillPreview) : "先选字段并查缺口。我会找最近一次记录，建议从它后一天开始补。"; }
    function ensureTrendDefaults() { var defs = sortPinnedFirst(editableDefs()); var preferred = ["atomoxetine_total_mg", "main_sleep_hours", "body_weight_clothed_jin", "blood_glucose_yuyue550"]; if (!state.trend.metric || !findDef(state.trend.metric)) { var found = preferred.map(findDef).filter(Boolean)[0] || defs[0]; state.trend.metric = (found || {}).metric_key || ""; } if (!state.trend.days) state.trend.days = 90; }
    function fillTrendControls() { ensureTrendDefaults(); var metric = document.getElementById("trendMetric"); if (metric) metric.value = state.trend.metric; }
    function trendTitle() { var def = findDef(state.trend.metric); return def ? cleanLabel(def) : "选择字段"; }
    async function loadTrend() { ensureTrendDefaults(); if (!state.trend.metric) return; var seq = ++trendLoadSeq; var metric = state.trend.metric; var days = Number(state.trend.days || 90); var date = state.date; var cacheKey = trendCacheKey(metric, days, date); var cached = readJson(cacheKey); if (cached && cached.data && cached.data.metric_key === metric && !state.trend.data) { state.trend.data = cached.data; renderAll(); } state.trend.loading = true; renderAll(); try { var data = await api("/api/history?metric_key=" + encodeURIComponent(metric) + "&days=" + encodeURIComponent(days) + "&end_date=" + encodeURIComponent(date)); if (seq !== trendLoadSeq || state.trend.metric !== metric || Number(state.trend.days) !== days || state.date !== date) return; state.trend.data = data; localStorage.setItem(cacheKey, JSON.stringify({ cached_at: new Date().toISOString(), data: data })); setStatus("已读取"); } catch (err) { if (seq === trendLoadSeq) showToast("历史读取失败"); } finally { if (seq === trendLoadSeq) { state.trend.loading = false; renderAll(); } } }
    function trendCacheKey(metric, days, date) { return "metricsPwaHistory:" + metric + ":" + days + ":" + date; }
    function renderTrendStats(data) { var def = data.definition || findDef(data.metric_key) || {}; var stats = data.stats || {}; var cells = []; cells.push(["最近", displayValue(stats.last_value, def)]); if (def.value_type === "number") { cells.push(["均值", stats.avg == null ? "空" : displayValue(stats.avg, def)]); cells.push(["最低/最高", (stats.min == null ? "空" : stats.min) + " / " + (stats.max == null ? "空" : stats.max)]); cells.push(["变化", stats.delta == null ? "空" : displayValue(stats.delta, def)]); } else if (def.value_type === "boolean") { cells.push(["是/否", (stats.true_count || 0) + " / " + (stats.false_count || 0)]); cells.push(["覆盖", stats.count + "/" + stats.day_count + " 天"]); cells.push(["缺失", stats.missing_count + " 天"]); } else { cells.push(["记录数", stats.count + " 条"]); cells.push(["覆盖", stats.count + "/" + stats.day_count + " 天"]); cells.push(["缺失", stats.missing_count + " 天"]); } return '<div class="trend-stats">' + cells.map(function (cell) { return '<div class="trend-stat"><b>' + escapeHtml(cell[1]) + '</b><span>' + escapeHtml(cell[0]) + '</span></div>'; }).join("") + '</div>'; }
    function renderTrendChart(data) { var def = data.definition || {}; if (def.value_type !== "number") return renderBoolTimeline(data); var rows = (data.rows || []).filter(function (row) { return typeof row.value === "number"; }); if (rows.length < 2) return '<div class="chart-empty">数值记录不足，至少 2 条后才能画趋势。</div>'; var values = rows.map(function (row) { return row.value; }); var min = Math.min.apply(null, values); var max = Math.max.apply(null, values); if (min === max) { min -= 1; max += 1; } var w = 640, h = 220, pad = 28; var points = rows.map(function (row, index) { var x = pad + (w - pad * 2) * (rows.length === 1 ? 0 : index / (rows.length - 1)); var y = h - pad - (h - pad * 2) * ((row.value - min) / (max - min)); return roundNumber(x) + "," + roundNumber(y); }).join(" "); var last = rows[rows.length - 1]; return '<svg class="chart" viewBox="0 0 ' + w + ' ' + h + '" preserveAspectRatio="none" role="img" aria-label="趋势图"><line x1="' + pad + '" y1="' + (h - pad) + '" x2="' + (w - pad) + '" y2="' + (h - pad) + '" stroke="#d7dde5" stroke-width="2"/><line x1="' + pad + '" y1="' + pad + '" x2="' + (w - pad) + '" y2="' + pad + '" stroke="#eef2f6" stroke-width="2"/><polyline points="' + points + '" fill="none" stroke="#0f766e" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><circle cx="' + points.split(" ").pop().split(",")[0] + '" cy="' + points.split(" ").pop().split(",")[1] + '" r="7" fill="#0f766e"/><text x="' + pad + '" y="20" fill="#667085" font-size="18">' + escapeHtml(String(max)) + '</text><text x="' + pad + '" y="' + (h - 6) + '" fill="#667085" font-size="18">' + escapeHtml(String(min)) + '</text><text x="' + (w - pad - 120) + '" y="24" fill="#111827" font-size="18">' + escapeHtml(shortDate(last.local_date) + " " + displayValue(last.value, def)) + '</text></svg>'; }
    function renderBoolTimeline(data) { var rows = data.rows || []; if (!rows.length) return '<div class="chart-empty">这个范围内没有记录。</div>'; var def = data.definition || {}; return '<div class="history-list">' + rows.slice(-8).reverse().map(function (row) { return '<div class="history-row"><div class="date">' + escapeHtml(row.local_date) + '</div><div class="value">' + escapeHtml(displayValue(row.value, def)) + '</div><div class="source">' + escapeHtml(row.source || "") + '</div></div>'; }).join("") + '</div>'; }
    function renderHistoryGrid(data) { var dates = enumerateDateStrings(data.start_date, data.end_date); var byDate = {}; (data.rows || []).forEach(function (row) { byDate[row.local_date] = row; }); var numeric = (data.rows || []).map(function (row) { return Number(row.value); }).filter(function (value) { return Number.isFinite(value); }); var min = numeric.length ? Math.min.apply(null, numeric) : 0; var max = numeric.length ? Math.max.apply(null, numeric) : 1; return '<div class="history-grid">' + dates.map(function (date) { var row = byDate[date]; var cls = 'history-cell'; if (row) { cls += ' has'; if (typeof row.value === "number" && max > min) { var ratio = (row.value - min) / (max - min); cls += ratio < .34 ? ' low' : ratio < .67 ? ' mid' : ''; } } return '<span class="' + cls + '" title="' + escapeAttr(date + (row ? ' ' + displayValue(row.value, data.definition) : ' 空')) + '"></span>'; }).join("") + '</div>'; }
    function renderHistoryRows(data) { var def = data.definition || {}; var rows = (data.rows || []).slice(-14).reverse(); if (!rows.length) return '<div class="empty">这个范围内没有记录。</div>'; return '<div class="history-list">' + rows.map(function (row) { return '<div class="history-row"><div class="date">' + escapeHtml(row.local_date) + '</div><div class="value">' + escapeHtml(displayValue(row.value, def)) + '</div><div class="source">' + escapeHtml(row.source || "") + '</div></div>'; }).join("") + '</div>'; }
    function renderDenseFilled(defs) { return '<div class="dense-list">' + defs.map(function (def) { var value = valueFor(def); var expanded = !!state.expanded[def.metric_key]; var pinned = state.pinned.indexOf(def.metric_key) !== -1; return '<article class="dense-row ' + (expanded ? 'expanded' : '') + '" data-metric="' + escapeAttr(def.metric_key) + '"><button class="star ' + (pinned ? 'on' : '') + '" type="button" data-pin="' + escapeAttr(def.metric_key) + '">★</button><div><div class="dense-label">' + escapeHtml(cleanLabel(def)) + '</div><div class="dense-sub">' + escapeHtml((CATEGORY_NAMES[def.category] || def.category || '其他') + (def.unit ? ' · ' + def.unit : '')) + '</div></div><div class="dense-value">' + escapeHtml(displayValue(value, def)) + '</div><button class="icon" type="button" data-info="' + escapeAttr(def.metric_key) + '">i</button>' + renderMetricDetail(def) + '</article>'; }).join("") + '</div>'; }
    function renderMetric(def) { var value = valueFor(def); var dirty = Object.prototype.hasOwnProperty.call(state.dirty, def.metric_key); var expanded = !!state.expanded[def.metric_key]; var pinned = state.pinned.indexOf(def.metric_key) !== -1; return '<article class="metric ' + (dirty ? 'dirty ' : '') + (expanded ? 'expanded' : '') + '" data-metric="' + escapeAttr(def.metric_key) + '"><div class="metric-main"><div class="metric-title-row"><button class="star ' + (pinned ? 'on' : '') + '" type="button" data-pin="' + escapeAttr(def.metric_key) + '" aria-label="常用">★</button><div><div class="metric-name">' + escapeHtml(cleanLabel(def)) + '</div><div class="metric-desc">' + escapeHtml(compactMeta(def)) + '</div></div><button class="icon" type="button" data-info="' + escapeAttr(def.metric_key) + '" aria-label="字段说明">i</button></div>' + renderMetricContext(def, value) + '</div><div class="metric-control">' + renderControl(def, value) + '</div>' + renderMetricDetail(def) + '</article>'; }
    function renderControl(def, value) { if (timeRangeConfig(def)) return renderTimeRangeControl(def, value); if (def.value_type === "boolean") return renderBool(def, value); if (def.value_type === "text") return '<input class="metric-input" data-key="' + escapeAttr(def.metric_key) + '" value="' + escapeAttr(value == null ? "" : value) + '" placeholder="输入文本">'; if (def.value_type === "number") return renderNumber(def, value); return '<textarea class="metric-input" data-key="' + escapeAttr(def.metric_key) + '" placeholder="输入文本或 JSON">' + escapeHtml(value == null ? "" : typeof value === "object" ? JSON.stringify(value) : value) + '</textarea>'; }
    function renderNumber(def, value) { var step = stepFor(def); return '<div class="number-control"><button type="button" data-step="' + escapeAttr(def.metric_key) + '" data-delta="-' + step + '">−</button><input class="metric-input" data-key="' + escapeAttr(def.metric_key) + '" type="number" inputmode="decimal" step="' + step + '" value="' + escapeAttr(value == null ? "" : value) + '"><button type="button" data-step="' + escapeAttr(def.metric_key) + '" data-delta="' + step + '">+</button></div>'; }
    function renderBool(def, value) { var current = value === true ? "true" : value === false ? "false" : ""; return '<div class="tri"><button type="button" data-bool="' + escapeAttr(def.metric_key) + '" data-value="" class="' + (current === "" ? "active" : "") + '">—</button><button type="button" data-bool="' + escapeAttr(def.metric_key) + '" data-value="false" class="' + (current === "false" ? "active" : "") + '">否</button><button type="button" data-bool="' + escapeAttr(def.metric_key) + '" data-value="true" class="' + (current === "true" ? "active" : "") + '">是</button></div>'; }
    function timeRangeConfig(def) { if (!def) return null; var md = def.metadata || {}; var key = def.metric_key || ""; var detailKey = md.time_range_detail_key || ""; var defaults = { step: Number(md.range_step_minutes || 15), start: md.range_default_start || "10:00", end: md.range_default_end || "11:00" }; if (!detailKey && key === "main_sleep_hours") { detailKey = "main_sleep_time_ranges"; defaults = { step: 15, start: "23:30", end: "07:30" }; } if (!detailKey && key === "work_hours") { detailKey = "work_time_ranges"; defaults = { step: 15, start: "10:00", end: "12:00" }; } if (!detailKey && key === "pre_sleep_info_flow_minutes") { detailKey = "pre_sleep_info_flow_time_ranges"; defaults = { step: 10, start: "22:30", end: "23:00" }; } if (!detailKey) return null; return { detailKey: detailKey, step: Math.max(5, Math.min(Number(defaults.step || 15), 60)), defaultStart: defaults.start, defaultEnd: defaults.end, unit: def.unit || "minute" }; }
    function renderTimeRangeControl(def, value) { var cfg = timeRangeConfig(def); var ranges = timeRangesForDef(def, value); var total = summarizeRanges(def, ranges); var max = 1439; return '<div class="time-range" data-time-range="' + escapeAttr(def.metric_key) + '" data-detail-key="' + escapeAttr(cfg.detailKey) + '" data-step="' + escapeAttr(cfg.step) + '"><div class="time-range-summary" data-time-range-summary="' + escapeAttr(def.metric_key) + '">' + escapeHtml(total.label) + '</div>' + ranges.map(function (range, index) { return renderTimeRangeRow(def, range, index, cfg, max); }).join("") + '<button class="tiny accent" type="button" data-time-range-add="' + escapeAttr(def.metric_key) + '">增加一段</button></div>'; }
    function renderTimeRangeRow(def, range, index, cfg, max) { var sd = dayOffset(range.start), ed = dayOffset(range.end), cross = sd !== ed; return '<div class="time-range-row" data-range-index="' + index + '" data-start-day="' + sd + '" data-end-day="' + ed + '"><div class="time-range-times"><button class="tiny" type="button" data-time-nudge="' + escapeAttr(def.metric_key) + '" data-range-index="' + index + '" data-bound="start" data-delta="' + (-cfg.step) + '">−</button><b data-time-label="start">' + escapeHtml(dayTime(range.start)) + '</b><button class="tiny" type="button" data-time-nudge="' + escapeAttr(def.metric_key) + '" data-range-index="' + index + '" data-bound="start" data-delta="' + cfg.step + '">+</button><span>到</span><button class="tiny" type="button" data-time-nudge="' + escapeAttr(def.metric_key) + '" data-range-index="' + index + '" data-bound="end" data-delta="' + (-cfg.step) + '">−</button><b data-time-label="end">' + escapeHtml(dayTime(range.end)) + '</b><button class="tiny" type="button" data-time-nudge="' + escapeAttr(def.metric_key) + '" data-range-index="' + index + '" data-bound="end" data-delta="' + cfg.step + '">+</button><button class="tiny danger" type="button" data-time-range-delete="' + escapeAttr(def.metric_key) + '" data-range-index="' + index + '">删</button></div><button class="tiny time-range-day" type="button" data-time-range-day="' + escapeAttr(def.metric_key) + '" data-range-index="' + index + '"' + (cross ? ' disabled' : '') + '>' + (cross ? '跨日' : sd ? '次日' : '本日') + '</button><input class="time-range-slider" type="range" min="0" max="' + max + '" step="' + escapeAttr(cfg.step) + '" value="' + escapeAttr(wrapMinute(range.start)) + '" data-time-range-input="' + escapeAttr(def.metric_key) + '" data-range-index="' + index + '" data-bound="start"><input class="time-range-slider" type="range" min="0" max="' + max + '" step="' + escapeAttr(cfg.step) + '" value="' + escapeAttr(wrapMinute(range.end)) + '" data-time-range-input="' + escapeAttr(def.metric_key) + '" data-range-index="' + index + '" data-bound="end"><div class="time-range-duration" data-time-duration>' + escapeHtml(formatRangeDuration(range)) + '</div></div>'; }
    function timeRangesForDef(def, value) { var cfg = timeRangeConfig(def); var detailDef = findDef(cfg.detailKey); var detailValue = detailDef ? valueFor(detailDef) : null; var ranges = parseRanges(detailValue); if (!ranges.length && typeof value === "number" && value > 0) ranges = deriveRangeFromTotal(def, value, cfg); if (!ranges.length) ranges = [{ start: minuteFromTime(cfg.defaultStart), end: minuteFromTime(cfg.defaultEnd) }]; return ranges.map(normalizeRange).filter(Boolean); }
    function parseRanges(value) { var raw = value && value.ranges ? value.ranges : value; if (!Array.isArray(raw)) return []; return raw.map(function (item) { return normalizeRange({ start: item.start, end: item.end, start_day_offset: item.start_day_offset, end_day_offset: item.end_day_offset }); }).filter(Boolean); }
    function deriveRangeFromTotal(def, value, cfg) { var minutes = def.unit === "minute" ? Number(value) : Number(value) * 60; if (!Number.isFinite(minutes) || minutes <= 0) return []; var end = minuteFromTime(cfg.defaultEnd); var start = wrapMinute(end - Math.round(minutes)); return [{ start: start, end: end }]; }
    function normalizeRange(range) { var start = minuteFromTime(range.start); var end = minuteFromTime(range.end); if (!Number.isFinite(start) || !Number.isFinite(end)) return null; var hs = Object.prototype.hasOwnProperty.call(range, "start_day_offset"), he = Object.prototype.hasOwnProperty.call(range, "end_day_offset"); start = typeof range.start === "number" && !hs ? Math.max(0, start) : wrapMinute(start) + Number(range.start_day_offset || 0) * 1440; end = typeof range.end === "number" && !he ? Math.max(0, end) : wrapMinute(end) + Number(range.end_day_offset || 0) * 1440; if (!he && end < start) end += 1440; return { start: start, end: end }; }
    function collectTimeRangeRows(container) { return Array.from(container.querySelectorAll(".time-range-row")).map(function (row) { var start = row.querySelector('[data-bound="start"][data-time-range-input]'); var end = row.querySelector('[data-bound="end"][data-time-range-input]'); return normalizeRange({ start: start && start.value, end: end && end.value, start_day_offset: row.dataset.startDay, end_day_offset: row.dataset.endDay }); }).filter(Boolean); }
    function applyTimeRangeFromDom(key) { var def = findDef(key); var container = el.content.querySelector('[data-time-range="' + cssEscape(key) + '"]'); if (!def || !container) return; var ranges = collectTimeRangeRows(container); updateTimeRangeDom(def, container, ranges); setTimeRangeDirty(def, ranges); refreshMetricContext(def); }
    function updateTimeRangeDom(def, container, ranges) { var total = summarizeRanges(def, ranges); var summary = container.querySelector("[data-time-range-summary]"); if (summary) summary.textContent = total.label; Array.from(container.querySelectorAll(".time-range-row")).forEach(function (row, index) { var range = ranges[index]; if (!range) return; row.dataset.startDay = dayOffset(range.start); row.dataset.endDay = dayOffset(range.end); var start = row.querySelector('[data-time-label="start"]'); var end = row.querySelector('[data-time-label="end"]'); var duration = row.querySelector("[data-time-duration]"); if (start) start.textContent = dayTime(range.start); if (end) end.textContent = dayTime(range.end); if (duration) duration.textContent = formatRangeDuration(range); }); }
    function setTimeRangeDirty(def, ranges) { var cfg = timeRangeConfig(def); var total = summarizeRanges(def, ranges); state.dirty[def.metric_key] = total.value; if (findDef(cfg.detailKey)) state.dirty[cfg.detailKey] = { kind: "time_ranges", total_metric_key: def.metric_key, unit: def.unit || null, total_minutes: total.minutes, total_hours: roundNumber(total.minutes / 60), ranges: ranges.map(function (range) { return { start: minuteToTime(range.start), end: minuteToTime(range.end), start_day_offset: dayOffset(range.start), end_day_offset: dayOffset(range.end), minutes: durationMinutes(range) }; }) }; setStatus("未保存"); renderTodayPanel(); renderFilters(); updateFooter(); }
    function refreshMetricContext(def) { var article = el.content.querySelector('[data-metric="' + cssEscape(def.metric_key) + '"]'); var context = article && article.querySelector(".metric-context"); if (context) context.outerHTML = renderMetricContext(def, valueFor(def)); }
    function addTimeRange(key) { var def = findDef(key); if (!def) return; var ranges = timeRangesForDef(def, valueFor(def)); var cfg = timeRangeConfig(def); var last = ranges[ranges.length - 1] || { end: minuteFromTime(cfg.defaultStart) }; ranges.push({ start: last.end, end: last.end + 60 }); setTimeRangeDirty(def, ranges); renderAll(); }
    function deleteTimeRange(key, index) { var def = findDef(key); if (!def) return; var ranges = timeRangesForDef(def, valueFor(def)); if (ranges.length <= 1) ranges = [{ start: minuteFromTime(timeRangeConfig(def).defaultStart), end: minuteFromTime(timeRangeConfig(def).defaultStart) }]; else ranges.splice(index, 1); setTimeRangeDirty(def, ranges); renderAll(); }
    function toggleTimeRangeDay(key, index) { var def = findDef(key); if (!def) return; var ranges = timeRangesForDef(def, valueFor(def)); var range = ranges[index]; if (!range || dayOffset(range.start) !== dayOffset(range.end)) return; var delta = dayOffset(range.start) ? -1440 : 1440; range.start += delta; range.end += delta; setTimeRangeDirty(def, ranges); renderAll(); }
    function nudgeTimeRange(key, index, bound, delta) { var def = findDef(key); if (!def) return; var ranges = timeRangesForDef(def, valueFor(def)); if (!ranges[index]) return; ranges[index][bound] = Math.max(0, ranges[index][bound] + delta); if (ranges[index].end < ranges[index].start) ranges[index].end += 1440; setTimeRangeDirty(def, ranges); renderAll(); }
    function summarizeRanges(def, ranges) { var minutes = ranges.reduce(function (sum, range) { return sum + durationMinutes(range); }, 0); var value = def.unit === "minute" ? minutes : roundNumber(minutes / 60); return { minutes: minutes, value: value, label: "总计 " + (def.unit === "minute" ? minutes + " 分钟" : roundNumber(minutes / 60) + " 小时") }; }
    function durationMinutes(range) { var delta = range.end - range.start; if (delta < 0) delta += 1440; return delta; }
    function formatRangeDuration(range) { return dayTime(range.start) + " - " + dayTime(range.end) + " · " + durationMinutes(range) + " 分钟"; }
    function minuteFromTime(value) { if (typeof value === "number") return Math.round(value); var raw = String(value || "0:00").trim(); if (/^\d+$/.test(raw)) return Number(raw); var match = raw.match(/^(\d{1,2}):(\d{2})$/); if (!match) return 0; return Number(match[1]) * 60 + Number(match[2]); }
    function minuteToTime(minute) { minute = wrapMinute(minute); return String(Math.floor(minute / 60)).padStart(2, "0") + ":" + String(minute % 60).padStart(2, "0"); }
    function dayOffset(minute) { return Math.floor(Math.max(0, Number(minute || 0)) / 1440); }
    function dayTime(minute) { return (dayOffset(minute) ? "次日 " : "") + minuteToTime(minute); }
    function wrapMinute(minute) { minute = Math.round(Number(minute || 0)); return ((minute % 1440) + 1440) % 1440; }
    function renderMetricContext(def, value) { if (dirtyMetricKey(def.metric_key)) return '<div class="metric-context dirty-sync"><div class="context-text">未保存：<strong>' + escapeHtml(displayValue(value, def)) + '</strong></div></div>'; if (pendingMetricKey(def.metric_key)) return '<div class="metric-context pending-sync"><div class="context-text">待同步：<strong>' + escapeHtml(displayValue(value, def)) + '</strong></div></div>'; if (hasValueFor(def)) return '<div class="metric-context"><div class="context-text">数据库：<strong>' + escapeHtml(displayValue(value, def)) + '</strong></div></div>'; var latest = latestFor(def); if (latest) return '<div class="metric-context"><div class="context-text">上次 ' + escapeHtml(shortDate(latest.local_date)) + '：<strong>' + escapeHtml(displayValue(latest.value, def)) + '</strong></div><button class="tiny accent" type="button" data-use-latest="' + escapeAttr(def.metric_key) + '">沿用</button></div>'; return '<div class="metric-context"><div class="context-text">暂无历史值，手动填一次后以后可沿用。</div></div>'; }
    function renderMetricDetail(def) { var lines = []; lines.push('<div><strong>说明：</strong>' + escapeHtml(def.description || '数据库暂无说明') + '</div>'); lines.push('<div><strong>字段：</strong><code>' + escapeHtml(def.metric_key) + '</code></div>'); lines.push('<div><strong>格式：</strong>' + escapeHtml(def.value_type + (def.unit ? ' · ' + def.unit : '') + ' · ' + (CATEGORY_NAMES[def.category] || def.category || '其他')) + '</div>'); if (def.aliases && def.aliases.length) lines.push('<div><strong>别名：</strong>' + escapeHtml(def.aliases.join(' / ')) + '</div>'); if (def.source_headers && def.source_headers.length) lines.push('<div><strong>原表头：</strong>' + escapeHtml(def.source_headers.join(' / ')) + '</div>'); if (def.aggregation_method) lines.push('<div><strong>聚合：</strong>' + escapeHtml(def.aggregation_method) + '</div>'); var md = def.metadata || {}; if (md.note) lines.push('<div><strong>写入备注：</strong>' + escapeHtml(String(md.note)) + '</div>'); if (md.write_kind || md.write_action || md.source_column) lines.push('<div><strong>元数据：</strong>' + escapeHtml([md.write_kind, md.write_action, md.source_column && '列 ' + md.source_column].filter(Boolean).join(' · ')) + '</div>'); if (md.write_format) lines.push('<div><strong>写入样例：</strong><pre>' + escapeHtml(JSON.stringify(md.write_format, null, 2)) + '</pre></div>'); return '<div class="metric-detail"><div class="detail-grid">' + lines.join("") + '</div></div>'; }
    function handleInput(event) { if (event.target && event.target.id === "backfillValue") { state.backfill.value = event.target.value; return; } var timeInput = event.target.closest("[data-time-range-input]"); if (timeInput) { applyTimeRangeFromDom(timeInput.dataset.timeRangeInput); return; } var input = event.target.closest(".metric-input"); if (!input) return; var key = input.dataset.key; var def = findDef(key); if (!def) return; var value = input.value; if (value === "") setDirty(key, null); else if (def.value_type === "number") setDirty(key, Number(value)); else setDirty(key, value); }
    function handleChange(event) { if (!event.target) return; var timeInput = event.target.closest("[data-time-range-input]"); if (timeInput) { applyTimeRangeFromDom(timeInput.dataset.timeRangeInput); return; } if (event.target.id === "trendMetric") { state.trend.metric = event.target.value; state.trend.data = null; localStorage.setItem("metricsPwaTrendMetric", state.trend.metric); renderAll(); loadTrend(); } if (event.target.id === "backfillMetric") { state.backfill.metric = event.target.value; state.backfillPreview = null; state.backfillTouchedStart = false; } if (event.target.id === "backfillValue") state.backfill.value = event.target.value; if (event.target.id === "backfillStart") { state.backfill.start = event.target.value; state.backfillTouchedStart = true; } if (event.target.id === "backfillEnd") state.backfill.end = event.target.value; }
    function handleSheetClick(event) { var button = event.target.closest("[data-sheet-action]"); if (!button) { if (event.target === el.appSheet) closeSheet(); return; } var action = button.dataset.sheetAction; if (action === "close") closeSheet(); if (action === "sync") { closeSheet(); syncAll(); } if (action === "clear-cache") clearLocalCache(); if (action === "reload") window.location.reload(); if (action === "logout") logout(); if (action === "save-mindful") saveMindfulEdit(); }
    function handleMindfulPointerDown(event) { if (!isMindfulActiveView()) return; if (event.target.closest("[data-mindful-end-hold]")) return; event.preventDefault(); event.stopPropagation(); recordMindfulReturnNow(); }
    function handleMindfulEndHoldStart(event) { if (!isMindfulActiveView()) return; var button = event.target.closest("[data-mindful-end-hold]"); if (!button || state.mindfulAction) return; event.preventDefault(); event.stopPropagation(); clearMindfulEndHold(); button.classList.add("holding"); mindfulEndHoldTimer = setTimeout(function () { mindfulEndHoldTimer = null; button.classList.remove("holding"); if (navigator.vibrate) navigator.vibrate(35); runMindfulAction("end"); }, 1300); }
    function handleMindfulContextMenu(event) { if (!isMindfulActiveView()) return; event.preventDefault(); event.stopPropagation(); }
    function clearMindfulEndHold() { if (mindfulEndHoldTimer) { clearTimeout(mindfulEndHoldTimer); mindfulEndHoldTimer = null; } var button = document.querySelector("[data-mindful-end-hold].holding"); if (button) button.classList.remove("holding"); }
    function handleClick(event) { var recordTab = event.target.closest("[data-record-filter]"); if (recordTab) { selectRecordFilter(recordTab.dataset.recordFilter); return; } var timeAdd = event.target.closest("[data-time-range-add]"); if (timeAdd) { addTimeRange(timeAdd.dataset.timeRangeAdd); return; } var timeDel = event.target.closest("[data-time-range-delete]"); if (timeDel) { deleteTimeRange(timeDel.dataset.timeRangeDelete, Number(timeDel.dataset.rangeIndex || 0)); return; } var timeDay = event.target.closest("[data-time-range-day]"); if (timeDay) { toggleTimeRangeDay(timeDay.dataset.timeRangeDay, Number(timeDay.dataset.rangeIndex || 0)); return; } var timeNudge = event.target.closest("[data-time-nudge]"); if (timeNudge) { nudgeTimeRange(timeNudge.dataset.timeNudge, Number(timeNudge.dataset.rangeIndex || 0), timeNudge.dataset.bound, Number(timeNudge.dataset.delta || 0)); return; } var edit = event.target.closest("[data-mindful-edit]"); if (edit) { openMindfulEdit(edit.dataset.mindfulEdit); return; } var del = event.target.closest("[data-mindful-delete]"); if (del) { deleteMindfulSession(del.dataset.mindfulDelete); return; } var mindful = event.target.closest("[data-mindful-action]"); if (mindful) { runMindfulAction(mindful.dataset.mindfulAction); return; } var trendDays = event.target.closest("[data-trend-days]"); if (trendDays) { state.trend.days = Number(trendDays.dataset.trendDays || 90); state.trend.data = null; localStorage.setItem("metricsPwaTrendDays", String(state.trend.days)); renderAll(); loadTrend(); return; } var pin = event.target.closest("[data-pin]"); if (pin) { togglePinned(pin.dataset.pin); return; } var useLatest = event.target.closest("[data-use-latest]"); if (useLatest) { applyLatest(useLatest.dataset.useLatest); return; } var info = event.target.closest("[data-info]"); if (info) { state.expanded[info.dataset.info] = !state.expanded[info.dataset.info]; renderAll(); return; } var step = event.target.closest("[data-step]"); if (step) { var key = step.dataset.step; var input = el.content.querySelector('input[data-key="' + cssEscape(key) + '"]'); var current = Number(input && input.value || 0); var next = roundNumber(current + Number(step.dataset.delta || 0)); if (input) input.value = String(next); setDirty(key, next); renderAll(); return; } var bool = event.target.closest("[data-bool]"); if (bool) { var raw = bool.dataset.value; var value = raw === "" ? null : raw === "true"; setDirty(bool.dataset.bool, value); renderAll(); return; } if (event.target.closest("#previewBackfill")) { previewBackfill(); return; } if (event.target.closest("#runBackfill")) { runBackfill(); return; } }
    function setDirty(key, value) { state.dirty[key] = value; setStatus("未保存"); renderTodayPanel(); renderFilters(); updateFooter(); }
    function undoDirty() { state.dirty = {}; renderAll(); setStatus("已读取"); showToast("已撤销未保存改动"); }
    function applyLatest(key) { var def = findDef(key); var latest = def && latestFor(def); if (!latest) return showToast("没有可沿用的历史值"); state.dirty[key] = latest.value; setStatus("未保存"); renderAll(); showToast("已沿用上次值"); }
    function useLatestForPinned() { var applied = 0; pinnedDefs().forEach(function (def) { var latest = latestFor(def); if (!hasValueFor(def) && latest) { state.dirty[def.metric_key] = latest.value; applied += 1; } }); if (!applied) return showToast("没有可沿用的常用项"); setStatus("未保存"); renderAll(); showToast("已沿用 " + applied + " 项，确认后保存"); }
    async function runMindfulAction(action) { if (action === "return") return recordMindfulReturnNow(); if (action === "end") return endMindfulSession(); if (state.mindfulAction || action !== "start") return; state.mindfulAction = true; optimisticMindfulStart(); try { var data = await api("/api/mindfulness/start", { method: "POST", body: JSON.stringify({}) }); state.mindfulness = data.today || state.mindfulness; saveMindfulnessCache(state.mindfulness && state.mindfulness.local_date, state.mindfulness); if (state.pendingMindfulReturns.length) scheduleMindfulReturnFlush(40); showToast(data.message || "正念已更新"); } catch (err) { showToast("正念启动失败，已回到本地缓存"); state.mindfulness = (readJson(cacheKeyForMindfulness(state.date)) || {}).today || null; } finally { state.mindfulAction = false; renderAll(); } }
    function optimisticMindfulStart() { var localDate = shanghaiDate(0); var now = new Date().toISOString(); state.date = localDate; el.dateInput.value = localDate; var today = state.mindfulness && state.mindfulness.local_date === localDate ? state.mindfulness : { local_date: localDate, summary: {}, sessions: [] }; var existing = (today.sessions || []).filter(function (session) { return session.status !== "active"; }); var summary = today.summary || {}; var session = { id: "local-" + Date.now(), started_at: now, ended_at: null, local_date: localDate, duration_seconds: 0, return_count: 0, status: "active", note: null, source: "pwa_local", metadata: { optimistic: true } }; state.mindfulness = { local_date: localDate, now: now, active_session: session, summary: { session_count: Number(summary.session_count || existing.length) + 1, return_count: Number(summary.return_count || 0), completed_seconds: Number(summary.completed_seconds || 0), active_seconds: 0, total_seconds: Number(summary.completed_seconds || 0), completed_minutes: Number(summary.completed_minutes || 0), total_minutes: Number(summary.completed_minutes || 0), return_density_per_minute: summary.return_density_per_minute || null }, sessions: [session].concat(existing) }; saveMindfulnessCache(localDate, state.mindfulness); renderAll(); }
    function recordMindfulReturnNow() { var active = mindfulActive(); if (!active) return showToast("没有进行中的正念"); var now = Date.now(); if (now - mindfulReturnClickAt < 80) return; mindfulReturnClickAt = now; state.pendingMindfulReturns.push({ id: uid(), session_id: active.metadata && active.metadata.optimistic ? null : active.id, occurred_at: new Date().toISOString() }); saveMindfulReturnEvents(); if (navigator.vibrate) navigator.vibrate(8); renderTodayPanel(); if (state.filter === "mindfulness") renderContent(); scheduleMindfulReturnFlush(220); }
    function scheduleMindfulReturnFlush(delay) { if (mindfulReturnSyncTimer) clearTimeout(mindfulReturnSyncTimer); mindfulReturnSyncTimer = setTimeout(function () { mindfulReturnSyncTimer = null; flushMindfulReturns(); }, delay); }
    async function flushMindfulReturns() { if (mindfulReturnSyncPromise) return await mindfulReturnSyncPromise; var active = mindfulActive(); if (!state.pendingMindfulReturns.length || !active) return true; if (active.metadata && active.metadata.optimistic) { scheduleMindfulReturnFlush(300); return true; } var batch = state.pendingMindfulReturns.slice(0, 20).map(function (event) { return Object.assign({}, event, { session_id: event.session_id || active.id }); }); state.pendingMindfulReturns = state.pendingMindfulReturns.slice(batch.length); state.inFlightMindfulReturns = state.inFlightMindfulReturns.concat(batch); saveMindfulReturnEvents(); state.syncingMindfulReturns = true; renderAll(); mindfulReturnSyncPromise = (async function () { try { var data = await api("/api/mindfulness/return", { method: "POST", body: JSON.stringify({ increment: batch.length, events: batch }) }); state.inFlightMindfulReturns = state.inFlightMindfulReturns.filter(function (event) { return !batch.some(function (sent) { return sent.id === event.id; }); }); saveMindfulReturnEvents(); state.mindfulness = data.today || state.mindfulness; saveMindfulnessCache(state.mindfulness && state.mindfulness.local_date, state.mindfulness); if (state.pendingMindfulReturns.length) scheduleMindfulReturnFlush(40); return true; } catch (err) { state.inFlightMindfulReturns = state.inFlightMindfulReturns.filter(function (event) { return !batch.some(function (sent) { return sent.id === event.id; }); }); state.pendingMindfulReturns = batch.concat(state.pendingMindfulReturns); saveMindfulReturnEvents(); setStatus("拉回待同步"); scheduleMindfulReturnFlush(1200); return false; } finally { state.syncingMindfulReturns = false; mindfulReturnSyncPromise = null; renderAll(); } })(); return await mindfulReturnSyncPromise; }
    async function flushAllMindfulReturns() { if (mindfulReturnSyncTimer) { clearTimeout(mindfulReturnSyncTimer); mindfulReturnSyncTimer = null; } var guard = 0; while (mindfulLocalReturns() && guard < 80) { var ok = await flushMindfulReturns(); if (!ok) return false; guard += 1; await new Promise(function (resolve) { setTimeout(resolve, 40); }); } return mindfulLocalReturns() === 0; }
    async function endMindfulSession() { if (state.mindfulAction) return; state.mindfulAction = true; renderAll(); try { var synced = await flushAllMindfulReturns(); if (!synced) { showToast("拉回待同步，稍后再结束"); return; } var data = await api("/api/mindfulness/end", { method: "POST", body: JSON.stringify({}) }); state.mindfulness = data.today || state.mindfulness; saveMindfulnessCache(state.mindfulness && state.mindfulness.local_date, state.mindfulness); showToast(data.message || "正念已更新"); loadDay().catch(function (err) { console.error(err); }); } catch (err) { showToast("没有进行中的正念"); } finally { state.mindfulAction = false; renderAll(); } }
    function closeSheet() { state.sheet = ""; state.mindfulEditId = ""; renderAll(); }
    function openMindfulEdit(id) { if (!findMindfulSession(id)) return showToast("没有找到这条会话"); state.mindfulEditId = id; state.sheet = "mindful-edit"; renderAll(); }
    function findMindfulSession(id) { var sessions = (state.mindfulness && state.mindfulness.sessions) || []; return sessions.find(function (session) { return session.id === id; }) || null; }
    async function saveMindfulEdit() { var id = state.mindfulEditId; var minutes = Number((document.getElementById("mindfulEditMinutes") || {}).value); var returns = Number((document.getElementById("mindfulEditReturns") || {}).value); var note = (document.getElementById("mindfulEditNote") || {}).value || ""; if (!id || !Number.isFinite(minutes) || minutes < 0 || !Number.isFinite(returns) || returns < 0) return showToast("编辑值不完整"); state.mindfulAction = true; try { var data = await api("/api/mindfulness/session/update", { method: "POST", body: JSON.stringify({ id: id, duration_minutes: minutes, return_count: returns, note: note }) }); state.mindfulness = data.today || state.mindfulness; saveMindfulnessCache(state.mindfulness && state.mindfulness.local_date, state.mindfulness); state.sheet = ""; state.mindfulEditId = ""; showToast(data.message || "正念会话已更新"); loadDay().catch(function (err) { console.error(err); }); } catch (err) { showToast("正念会话保存失败"); } finally { state.mindfulAction = false; renderAll(); } }
    async function deleteMindfulSession(id) { if (!id || !confirm("删除这条正念会话？")) return; state.mindfulAction = true; renderAll(); try { var data = await api("/api/mindfulness/session/delete", { method: "POST", body: JSON.stringify({ id: id }) }); state.mindfulness = data.today || state.mindfulness; saveMindfulnessCache(state.mindfulness && state.mindfulness.local_date, state.mindfulness); showToast(data.message || "正念会话已删除"); loadDay().catch(function (err) { console.error(err); }); } catch (err) { showToast("正念会话删除失败"); } finally { state.mindfulAction = false; renderAll(); } }
    function localStorageKeys() { var keys = []; for (var i = 0; i < localStorage.length; i += 1) keys.push(localStorage.key(i)); return keys.filter(Boolean); }
    function clearLocalCache() { var removed = 0; localStorageKeys().forEach(function (key) { if (key === "metricsPwaSchema" || key.indexOf("metricsPwaDay:") === 0 || key.indexOf("metricsPwaHistory:") === 0 || key.indexOf("metricsPwaMindfulness:") === 0) { localStorage.removeItem(key); removed += 1; } }); state.trend.data = null; closeSheet(); showToast("已清除 " + removed + " 条缓存"); loadSchema(); loadDay(); }
    async function logout() { try { await api("/api/logout", { method: "POST", body: JSON.stringify({}) }); } catch (_) {} state.token = ""; localStorage.removeItem("metricsPwaToken"); closeSheet(); showLogin(); }
    async function saveDirty() { var keys = Object.keys(state.dirty); if (!keys.length) return showToast("没有改动"); var snapshot = Object.assign({}, state.dirty); var date = state.date; var body = { local_date: date, metrics: snapshot }; state.dirty = {}; state.values = applyDayPatch(state.values, snapshot); saveDayOverlay(date, snapshot); renderAll(); try { var result = await sendOrQueue("/api/metrics", "POST", body); if (!result.queued) { dayWriteSeq += 1; updateDayCacheWithConfirmedMetrics(date, snapshot); markDayOverlaySynced(date, snapshot); } setStatus(result.queued ? "本地待同步" : "已同步"); updateFooter(); showToast(result.queued ? "已保存在本地队列，待同步" : "已保存 " + logicalSavedCount(keys) + " 项"); } catch (err) { setStatus("本地待同步"); updateFooter(); showToast("已保存在本地队列，待同步"); } }
    function logicalSavedCount(keys) { return keys.filter(function (key) { return !isCompanionMetricKey(key); }).length; }
    async function previewBackfill() { var metric = document.getElementById("backfillMetric").value; var start = document.getElementById("backfillStart").value; var end = document.getElementById("backfillEnd").value || state.date; state.backfill.metric = metric; state.backfill.start = start; state.backfill.end = end; state.backfill.value = document.getElementById("backfillValue").value; setStatus("查缺口"); var data = await api("/api/metric_gaps?metric_key=" + encodeURIComponent(metric) + "&start_date=" + encodeURIComponent(start) + "&end_date=" + encodeURIComponent(end)); state.backfillPreview = data; if (data.latest && !state.backfill.value) state.backfill.value = displayValue(data.latest.value, data.definition).replace(/ .*/, ""); if (data.latest && !state.backfillTouchedStart) { var suggested = addDays(data.latest.local_date, 1); if (suggested <= end) state.backfill.start = suggested; } renderAll(); setStatus("已预览"); }
    async function runBackfill() { var metric = document.getElementById("backfillMetric").value; var value = document.getElementById("backfillValue").value; var start = document.getElementById("backfillStart").value; var end = document.getElementById("backfillEnd").value || state.date; state.backfill = { metric: metric, value: value, start: start, end: end }; if (!metric || !value || !start || !end) return showToast("补录信息不完整"); var body = { metric_key: metric, value: castBackfillValue(metric, value), start_date: start, end_date: end, only_empty: true }; var result = await sendOrQueue("/api/backfill", "POST", body); showToast(result.queued ? "补录已排队" : "已补 " + result.inserted + " 天"); state.backfillPreview = null; await loadDay(); }
    function backfillPreviewText(data) { var latest = data.latest ? ('最近记录：' + data.latest.local_date + ' = ' + displayValue(data.latest.value, data.definition) + '<br>') : '最近没有找到记录<br>'; return latest + '范围：' + data.start_date + ' 到 ' + data.end_date + '<br>空白 ' + data.missing_count + ' 天，已有 ' + data.existing_count + ' 天。执行时只补空白，不覆盖已有记录。'; }
    function toggleBackfill() { state.backfillOpen = !state.backfillOpen; if (state.backfillOpen) { state.query = ""; el.searchInput.value = ""; var advanced = document.querySelector(".advanced-tools"); if (advanced) advanced.open = false; } renderAll(); if (state.backfillOpen) setTimeout(function () { var panel = document.querySelector(".backfill.open"); if (panel) panel.scrollIntoView({ block: "start", behavior: "smooth" }); }, 30); }
    function focusFirstMissing() { state.recordFilter = "unfilled"; state.filter = "unfilled"; localStorage.setItem("metricsPwaRecordFilter", state.recordFilter); localStorage.setItem("metricsPwaFilter", state.filter); renderAll(); setTimeout(function () { var first = document.querySelector('.metric input, .metric button[data-bool], .metric input[type="range"]'); if (first) first.focus(); }, 30); }
    function updateFooter() { var dirtyCount = logicalDirtyCount(); var pending = []; var overlayPending = localOverlayPendingCount(); if (state.queue.length) pending.push("待同步 " + state.queue.length); if (overlayPending) pending.push("字段 " + overlayPending); if (mindfulLocalReturns()) pending.push("拉回 " + mindfulLocalReturns()); if (localStorage.getItem("metricsPwaPinnedPending") === "1") pending.push("收藏"); el.pending.textContent = pending.length ? pending.join(" / ") : "无待同步"; el.saveBtn.textContent = dirtyCount ? "保存 " + dirtyCount : "保存"; el.undoBtn.classList.toggle("hidden", !Object.keys(state.dirty).length); el.dirtyLabel.textContent = dirtyCount ? "已改 " + dirtyCount + " 项" : "未修改"; }
    function localOverlayPendingCount() { var count = 0; localStorageKeys().forEach(function (key) { var overlay = key.indexOf("metricsPwaOverlay:") === 0 ? readJson(key) : null; if (overlay && overlay.synced === false) count += 1; }); return count; }
    function dirtyMetricKey(key) { return Object.prototype.hasOwnProperty.call(state.dirty, key); }
    function pendingMetricKey(key) { return Object.prototype.hasOwnProperty.call(pendingDayPatch(state.date), key); }
    function logicalDirtyCount() { return Object.keys(state.dirty).filter(function (key) { return !isCompanionMetricKey(key); }).length; }
    function appSection() { if (state.filter === "mindfulness") return "mindfulness"; if (state.filter === "trend") return "trend"; if (state.filter === "all" || state.filter.indexOf("cat:") === 0) return "fields"; return "records"; }
    function visibleDefs() { var defs = editableDefs(); var q = state.query.toLowerCase(); if (q) return defs.filter(function (def) { return searchText(def).indexOf(q) !== -1; }); if (appSection() === "records") { if (state.filter === "unfilled") return unfilledDefs(); if (state.filter === "pinned") return sortUnfilledFirst(pinnedDefs()); if (state.filter === "filled") return filledDefs(); } if (state.filter.indexOf("cat:") === 0) return sortUnfilledFirst(defsForCategory(state.filter.slice(4))); return sortUnfilledFirst(defs); }
    function editableDefs() { return state.defs.filter(function (d) { return d.category !== "strength_event" && d.category !== "medicine_event" && !isCompanionMetric(d); }); }
    function isCompanionMetric(def) { return !!(def && def.metadata && def.metadata.companion_of); }
    function isCompanionMetricKey(key) { return isCompanionMetric(findDef(key)); }
    function pinnedDefs() { var byKey = {}; editableDefs().forEach(function (def) { byKey[def.metric_key] = def; }); return state.pinned.map(function (key) { return byKey[key]; }).filter(Boolean); }
    function unfilledDefs() { return pinnedDefs().filter(function (def) { return !hasValueFor(def); }); }
    function filledDefs() { return editableDefs().filter(hasValueFor); }
    function defsForCategory(cat) { return editableDefs().filter(function (d) { return (d.category || "general") === cat; }); }
    function categories() { var cats = unique(editableDefs().map(function (d) { return d.category || "general"; })); cats.sort(function (a, b) { return orderIndex(a) - orderIndex(b); }); return cats; }
    function scopeTitle() { if (state.query) return '搜索“' + state.query + '”'; if (state.filter === "unfilled") return "待填常用"; if (state.filter === "pinned") return "常用记录"; if (state.filter === "filled") return "已填写记录"; if (state.filter.indexOf("cat:") === 0) return CATEGORY_NAMES[state.filter.slice(4)] || state.filter.slice(4); return appSection() === "fields" ? "字段库" : "全部字段"; }
    function helperText() { if (appSection() === "fields") return state.query ? "搜索字段、别名和写入说明" : "查看字段格式，伴随明细字段默认隐藏"; if (state.filter === "filled" && !state.query) return "紧凑查看已填"; if (state.filter === "unfilled") return "只显示常用未填"; return state.query ? "搜索覆盖全部字段" : "未填会排在前面"; }
    function togglePinned(key) { var index = state.pinned.indexOf(key); if (index === -1) state.pinned.unshift(key); else state.pinned.splice(index, 1); state.pinned = cleanPinnedKeys(state.pinned); savePinned(); renderAll(); savePreferences(); }
    function sortUnfilledFirst(defs) { return defs.slice().sort(function (a, b) { return Number(hasValueFor(a)) - Number(hasValueFor(b)); }); }
    function hasValueFor(def) { var value = valueFor(def); return !(value === null || value === undefined || value === ""); }
    function valueFor(def) { return Object.prototype.hasOwnProperty.call(state.dirty, def.metric_key) ? state.dirty[def.metric_key] : state.values[def.metric_key]; }
    function findDef(key) { return state.defs.find(function (d) { return d.metric_key === key; }); }
    function orderIndex(cat) { var index = CATEGORY_ORDER.indexOf(cat); return index === -1 ? 999 : index; }
    function unique(list) { return Array.from(new Set(list)); }
    function cleanLabel(def) { return String(def.label || def.metric_key).replace(/\n+/g, " ").replace(/\s+/g, " ").trim(); }
    function compactMeta(def) { return [CATEGORY_NAMES[def.category] || def.category || "其他", def.value_type, def.unit].filter(Boolean).join(" · "); }
    function latestFor(def) { return state.latest && state.latest[def.metric_key] ? state.latest[def.metric_key] : null; }
    function shortDate(date) { return String(date || "").slice(5); }
    function sortPinnedFirst(defs) { return defs.slice().sort(function (a, b) { var ap = state.pinned.indexOf(a.metric_key); var bp = state.pinned.indexOf(b.metric_key); ap = ap === -1 ? 9999 : ap; bp = bp === -1 ? 9999 : bp; return ap - bp || orderIndex(a.category) - orderIndex(b.category) || cleanLabel(a).localeCompare(cleanLabel(b)); }); }
    function searchText(def) { return [def.metric_key, def.label, def.description, def.unit, def.category, (def.aliases || []).join(" "), (def.source_headers || []).join(" ")].join(" ").toLowerCase(); }
    function displayValue(value, def) { if (value === true) return "是"; if (value === false) return "否"; if (value === null || value === undefined || value === "") return "空"; if (typeof value === "object") return JSON.stringify(value); return String(value) + (def && def.unit ? " " + def.unit : ""); }
    function castBackfillValue(metricKey, raw) { var def = findDef(metricKey); if (!def) return raw; if (def.value_type === "number") return Number(raw); if (def.value_type === "boolean") return /^(true|yes|1|是)$/i.test(String(raw)); return raw; }
    function stepFor(def) { var key = def.metric_key; if (key.indexOf("weight") !== -1 || key.indexOf("glucose") !== -1) return 0.1; if (key.indexOf("hours") !== -1) return 0.5; if (key.indexOf("_g") !== -1) return 50; if (def.unit === "scoop") return 0.25; return 1; }
    function roundNumber(value) { return Math.round(value * 100) / 100; }
    function escapeHtml(value) { return String(value == null ? "" : value).replace(/[&<>"']/g, function (char) { return ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]; }); }
    function escapeAttr(value) { return escapeHtml(value); }
    function cssEscape(value) { if (window.CSS && CSS.escape) return CSS.escape(value); return String(value).replace(/[^a-zA-Z0-9_-]/g, "\\$&"); }
    boot();
  })();
